// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd/cmd_gacha.proto

#ifndef PROTOBUF_cmd_2fcmd_5fgacha_2eproto__INCLUDED
#define PROTOBUF_cmd_2fcmd_5fgacha_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "define.pb.h"
// @@protoc_insertion_point(includes)
namespace proto {
class DoGachaReq;
class DoGachaReqDefaultTypeInternal;
extern DoGachaReqDefaultTypeInternal _DoGachaReq_default_instance_;
class DoGachaRsp;
class DoGachaRspDefaultTypeInternal;
extern DoGachaRspDefaultTypeInternal _DoGachaRsp_default_instance_;
class GachaInfo;
class GachaInfoDefaultTypeInternal;
extern GachaInfoDefaultTypeInternal _GachaInfo_default_instance_;
class GachaItem;
class GachaItemDefaultTypeInternal;
extern GachaItemDefaultTypeInternal _GachaItem_default_instance_;
class GachaOpenWishNotify;
class GachaOpenWishNotifyDefaultTypeInternal;
extern GachaOpenWishNotifyDefaultTypeInternal _GachaOpenWishNotify_default_instance_;
class GachaSimpleInfoNotify;
class GachaSimpleInfoNotifyDefaultTypeInternal;
extern GachaSimpleInfoNotifyDefaultTypeInternal _GachaSimpleInfoNotify_default_instance_;
class GachaTransferItem;
class GachaTransferItemDefaultTypeInternal;
extern GachaTransferItemDefaultTypeInternal _GachaTransferItem_default_instance_;
class GachaUpInfo;
class GachaUpInfoDefaultTypeInternal;
extern GachaUpInfoDefaultTypeInternal _GachaUpInfo_default_instance_;
class GachaWishReq;
class GachaWishReqDefaultTypeInternal;
extern GachaWishReqDefaultTypeInternal _GachaWishReq_default_instance_;
class GachaWishRsp;
class GachaWishRspDefaultTypeInternal;
extern GachaWishRspDefaultTypeInternal _GachaWishRsp_default_instance_;
class GetGachaInfoReq;
class GetGachaInfoReqDefaultTypeInternal;
extern GetGachaInfoReqDefaultTypeInternal _GetGachaInfoReq_default_instance_;
class GetGachaInfoRsp;
class GetGachaInfoRspDefaultTypeInternal;
extern GetGachaInfoRspDefaultTypeInternal _GetGachaInfoRsp_default_instance_;
}  // namespace proto

namespace proto {

namespace protobuf_cmd_2fcmd_5fgacha_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cmd_2fcmd_5fgacha_2eproto

enum GetGachaInfoReq_CmdId {
  GetGachaInfoReq_CmdId_NONE = 0,
  GetGachaInfoReq_CmdId_CMD_ID = 1572,
  GetGachaInfoReq_CmdId_ENET_CHANNEL_ID = 0,
  GetGachaInfoReq_CmdId_ENET_IS_RELIABLE = 1,
  GetGachaInfoReq_CmdId_IS_ALLOW_CLIENT = 1,
  GetGachaInfoReq_CmdId_GetGachaInfoReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GetGachaInfoReq_CmdId_GetGachaInfoReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GetGachaInfoReq_CmdId_IsValid(int value);
const GetGachaInfoReq_CmdId GetGachaInfoReq_CmdId_CmdId_MIN = GetGachaInfoReq_CmdId_NONE;
const GetGachaInfoReq_CmdId GetGachaInfoReq_CmdId_CmdId_MAX = GetGachaInfoReq_CmdId_CMD_ID;
const int GetGachaInfoReq_CmdId_CmdId_ARRAYSIZE = GetGachaInfoReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* GetGachaInfoReq_CmdId_descriptor();
inline const ::std::string& GetGachaInfoReq_CmdId_Name(GetGachaInfoReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    GetGachaInfoReq_CmdId_descriptor(), value);
}
inline bool GetGachaInfoReq_CmdId_Parse(
    const ::std::string& name, GetGachaInfoReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GetGachaInfoReq_CmdId>(
    GetGachaInfoReq_CmdId_descriptor(), name, value);
}
enum GetGachaInfoRsp_CmdId {
  GetGachaInfoRsp_CmdId_NONE = 0,
  GetGachaInfoRsp_CmdId_CMD_ID = 1598,
  GetGachaInfoRsp_CmdId_ENET_CHANNEL_ID = 0,
  GetGachaInfoRsp_CmdId_ENET_IS_RELIABLE = 1,
  GetGachaInfoRsp_CmdId_GetGachaInfoRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GetGachaInfoRsp_CmdId_GetGachaInfoRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GetGachaInfoRsp_CmdId_IsValid(int value);
const GetGachaInfoRsp_CmdId GetGachaInfoRsp_CmdId_CmdId_MIN = GetGachaInfoRsp_CmdId_NONE;
const GetGachaInfoRsp_CmdId GetGachaInfoRsp_CmdId_CmdId_MAX = GetGachaInfoRsp_CmdId_CMD_ID;
const int GetGachaInfoRsp_CmdId_CmdId_ARRAYSIZE = GetGachaInfoRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* GetGachaInfoRsp_CmdId_descriptor();
inline const ::std::string& GetGachaInfoRsp_CmdId_Name(GetGachaInfoRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    GetGachaInfoRsp_CmdId_descriptor(), value);
}
inline bool GetGachaInfoRsp_CmdId_Parse(
    const ::std::string& name, GetGachaInfoRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GetGachaInfoRsp_CmdId>(
    GetGachaInfoRsp_CmdId_descriptor(), name, value);
}
enum DoGachaReq_CmdId {
  DoGachaReq_CmdId_NONE = 0,
  DoGachaReq_CmdId_CMD_ID = 1512,
  DoGachaReq_CmdId_ENET_CHANNEL_ID = 0,
  DoGachaReq_CmdId_ENET_IS_RELIABLE = 1,
  DoGachaReq_CmdId_IS_ALLOW_CLIENT = 1,
  DoGachaReq_CmdId_DoGachaReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  DoGachaReq_CmdId_DoGachaReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool DoGachaReq_CmdId_IsValid(int value);
const DoGachaReq_CmdId DoGachaReq_CmdId_CmdId_MIN = DoGachaReq_CmdId_NONE;
const DoGachaReq_CmdId DoGachaReq_CmdId_CmdId_MAX = DoGachaReq_CmdId_CMD_ID;
const int DoGachaReq_CmdId_CmdId_ARRAYSIZE = DoGachaReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* DoGachaReq_CmdId_descriptor();
inline const ::std::string& DoGachaReq_CmdId_Name(DoGachaReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    DoGachaReq_CmdId_descriptor(), value);
}
inline bool DoGachaReq_CmdId_Parse(
    const ::std::string& name, DoGachaReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DoGachaReq_CmdId>(
    DoGachaReq_CmdId_descriptor(), name, value);
}
enum DoGachaRsp_CmdId {
  DoGachaRsp_CmdId_NONE = 0,
  DoGachaRsp_CmdId_CMD_ID = 1535,
  DoGachaRsp_CmdId_ENET_CHANNEL_ID = 0,
  DoGachaRsp_CmdId_ENET_IS_RELIABLE = 1,
  DoGachaRsp_CmdId_DoGachaRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  DoGachaRsp_CmdId_DoGachaRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool DoGachaRsp_CmdId_IsValid(int value);
const DoGachaRsp_CmdId DoGachaRsp_CmdId_CmdId_MIN = DoGachaRsp_CmdId_NONE;
const DoGachaRsp_CmdId DoGachaRsp_CmdId_CmdId_MAX = DoGachaRsp_CmdId_CMD_ID;
const int DoGachaRsp_CmdId_CmdId_ARRAYSIZE = DoGachaRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* DoGachaRsp_CmdId_descriptor();
inline const ::std::string& DoGachaRsp_CmdId_Name(DoGachaRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    DoGachaRsp_CmdId_descriptor(), value);
}
inline bool DoGachaRsp_CmdId_Parse(
    const ::std::string& name, DoGachaRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DoGachaRsp_CmdId>(
    DoGachaRsp_CmdId_descriptor(), name, value);
}
enum GachaWishReq_CmdId {
  GachaWishReq_CmdId_NONE = 0,
  GachaWishReq_CmdId_CMD_ID = 1507,
  GachaWishReq_CmdId_ENET_CHANNEL_ID = 0,
  GachaWishReq_CmdId_ENET_IS_RELIABLE = 1,
  GachaWishReq_CmdId_IS_ALLOW_CLIENT = 1,
  GachaWishReq_CmdId_GachaWishReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GachaWishReq_CmdId_GachaWishReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GachaWishReq_CmdId_IsValid(int value);
const GachaWishReq_CmdId GachaWishReq_CmdId_CmdId_MIN = GachaWishReq_CmdId_NONE;
const GachaWishReq_CmdId GachaWishReq_CmdId_CmdId_MAX = GachaWishReq_CmdId_CMD_ID;
const int GachaWishReq_CmdId_CmdId_ARRAYSIZE = GachaWishReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* GachaWishReq_CmdId_descriptor();
inline const ::std::string& GachaWishReq_CmdId_Name(GachaWishReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    GachaWishReq_CmdId_descriptor(), value);
}
inline bool GachaWishReq_CmdId_Parse(
    const ::std::string& name, GachaWishReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GachaWishReq_CmdId>(
    GachaWishReq_CmdId_descriptor(), name, value);
}
enum GachaWishRsp_CmdId {
  GachaWishRsp_CmdId_NONE = 0,
  GachaWishRsp_CmdId_CMD_ID = 1521,
  GachaWishRsp_CmdId_ENET_CHANNEL_ID = 0,
  GachaWishRsp_CmdId_ENET_IS_RELIABLE = 1,
  GachaWishRsp_CmdId_GachaWishRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GachaWishRsp_CmdId_GachaWishRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GachaWishRsp_CmdId_IsValid(int value);
const GachaWishRsp_CmdId GachaWishRsp_CmdId_CmdId_MIN = GachaWishRsp_CmdId_NONE;
const GachaWishRsp_CmdId GachaWishRsp_CmdId_CmdId_MAX = GachaWishRsp_CmdId_CMD_ID;
const int GachaWishRsp_CmdId_CmdId_ARRAYSIZE = GachaWishRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* GachaWishRsp_CmdId_descriptor();
inline const ::std::string& GachaWishRsp_CmdId_Name(GachaWishRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    GachaWishRsp_CmdId_descriptor(), value);
}
inline bool GachaWishRsp_CmdId_Parse(
    const ::std::string& name, GachaWishRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GachaWishRsp_CmdId>(
    GachaWishRsp_CmdId_descriptor(), name, value);
}
enum GachaOpenWishNotify_CmdId {
  GachaOpenWishNotify_CmdId_NONE = 0,
  GachaOpenWishNotify_CmdId_CMD_ID = 1503,
  GachaOpenWishNotify_CmdId_ENET_CHANNEL_ID = 0,
  GachaOpenWishNotify_CmdId_ENET_IS_RELIABLE = 1,
  GachaOpenWishNotify_CmdId_IS_ALLOW_CLIENT = 1,
  GachaOpenWishNotify_CmdId_GachaOpenWishNotify_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GachaOpenWishNotify_CmdId_GachaOpenWishNotify_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GachaOpenWishNotify_CmdId_IsValid(int value);
const GachaOpenWishNotify_CmdId GachaOpenWishNotify_CmdId_CmdId_MIN = GachaOpenWishNotify_CmdId_NONE;
const GachaOpenWishNotify_CmdId GachaOpenWishNotify_CmdId_CmdId_MAX = GachaOpenWishNotify_CmdId_CMD_ID;
const int GachaOpenWishNotify_CmdId_CmdId_ARRAYSIZE = GachaOpenWishNotify_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* GachaOpenWishNotify_CmdId_descriptor();
inline const ::std::string& GachaOpenWishNotify_CmdId_Name(GachaOpenWishNotify_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    GachaOpenWishNotify_CmdId_descriptor(), value);
}
inline bool GachaOpenWishNotify_CmdId_Parse(
    const ::std::string& name, GachaOpenWishNotify_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GachaOpenWishNotify_CmdId>(
    GachaOpenWishNotify_CmdId_descriptor(), name, value);
}
enum GachaSimpleInfoNotify_CmdId {
  GachaSimpleInfoNotify_CmdId_NONE = 0,
  GachaSimpleInfoNotify_CmdId_CMD_ID = 1590,
  GachaSimpleInfoNotify_CmdId_ENET_CHANNEL_ID = 0,
  GachaSimpleInfoNotify_CmdId_ENET_IS_RELIABLE = 1,
  GachaSimpleInfoNotify_CmdId_GachaSimpleInfoNotify_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GachaSimpleInfoNotify_CmdId_GachaSimpleInfoNotify_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GachaSimpleInfoNotify_CmdId_IsValid(int value);
const GachaSimpleInfoNotify_CmdId GachaSimpleInfoNotify_CmdId_CmdId_MIN = GachaSimpleInfoNotify_CmdId_NONE;
const GachaSimpleInfoNotify_CmdId GachaSimpleInfoNotify_CmdId_CmdId_MAX = GachaSimpleInfoNotify_CmdId_CMD_ID;
const int GachaSimpleInfoNotify_CmdId_CmdId_ARRAYSIZE = GachaSimpleInfoNotify_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* GachaSimpleInfoNotify_CmdId_descriptor();
inline const ::std::string& GachaSimpleInfoNotify_CmdId_Name(GachaSimpleInfoNotify_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    GachaSimpleInfoNotify_CmdId_descriptor(), value);
}
inline bool GachaSimpleInfoNotify_CmdId_Parse(
    const ::std::string& name, GachaSimpleInfoNotify_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GachaSimpleInfoNotify_CmdId>(
    GachaSimpleInfoNotify_CmdId_descriptor(), name, value);
}
// ===================================================================

class GetGachaInfoReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GetGachaInfoReq) */ {
 public:
  GetGachaInfoReq();
  virtual ~GetGachaInfoReq();

  GetGachaInfoReq(const GetGachaInfoReq& from);

  inline GetGachaInfoReq& operator=(const GetGachaInfoReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetGachaInfoReq(GetGachaInfoReq&& from) noexcept
    : GetGachaInfoReq() {
    *this = ::std::move(from);
  }

  inline GetGachaInfoReq& operator=(GetGachaInfoReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetGachaInfoReq& default_instance();

  static inline const GetGachaInfoReq* internal_default_instance() {
    return reinterpret_cast<const GetGachaInfoReq*>(
               &_GetGachaInfoReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(GetGachaInfoReq* other);
  friend void swap(GetGachaInfoReq& a, GetGachaInfoReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetGachaInfoReq* New() const PROTOBUF_FINAL { return New(NULL); }

  GetGachaInfoReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetGachaInfoReq& from);
  void MergeFrom(const GetGachaInfoReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetGachaInfoReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GetGachaInfoReq_CmdId CmdId;
  static const CmdId NONE =
    GetGachaInfoReq_CmdId_NONE;
  static const CmdId CMD_ID =
    GetGachaInfoReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    GetGachaInfoReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    GetGachaInfoReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    GetGachaInfoReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return GetGachaInfoReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    GetGachaInfoReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    GetGachaInfoReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    GetGachaInfoReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return GetGachaInfoReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return GetGachaInfoReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return GetGachaInfoReq_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:proto.GetGachaInfoReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fgacha_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GachaUpInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GachaUpInfo) */ {
 public:
  GachaUpInfo();
  virtual ~GachaUpInfo();

  GachaUpInfo(const GachaUpInfo& from);

  inline GachaUpInfo& operator=(const GachaUpInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GachaUpInfo(GachaUpInfo&& from) noexcept
    : GachaUpInfo() {
    *this = ::std::move(from);
  }

  inline GachaUpInfo& operator=(GachaUpInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GachaUpInfo& default_instance();

  static inline const GachaUpInfo* internal_default_instance() {
    return reinterpret_cast<const GachaUpInfo*>(
               &_GachaUpInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(GachaUpInfo* other);
  friend void swap(GachaUpInfo& a, GachaUpInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GachaUpInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  GachaUpInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GachaUpInfo& from);
  void MergeFrom(const GachaUpInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GachaUpInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 item_id_list = 15;
  int item_id_list_size() const;
  void clear_item_id_list();
  static const int kItemIdListFieldNumber = 15;
  ::google::protobuf::uint32 item_id_list(int index) const;
  void set_item_id_list(int index, ::google::protobuf::uint32 value);
  void add_item_id_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      item_id_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_item_id_list();

  // uint32 item_parent_type = 7;
  void clear_item_parent_type();
  static const int kItemParentTypeFieldNumber = 7;
  ::google::protobuf::uint32 item_parent_type() const;
  void set_item_parent_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.GachaUpInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > item_id_list_;
  mutable int _item_id_list_cached_byte_size_;
  ::google::protobuf::uint32 item_parent_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fgacha_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GachaInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GachaInfo) */ {
 public:
  GachaInfo();
  virtual ~GachaInfo();

  GachaInfo(const GachaInfo& from);

  inline GachaInfo& operator=(const GachaInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GachaInfo(GachaInfo&& from) noexcept
    : GachaInfo() {
    *this = ::std::move(from);
  }

  inline GachaInfo& operator=(GachaInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GachaInfo& default_instance();

  static inline const GachaInfo* internal_default_instance() {
    return reinterpret_cast<const GachaInfo*>(
               &_GachaInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(GachaInfo* other);
  friend void swap(GachaInfo& a, GachaInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GachaInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  GachaInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GachaInfo& from);
  void MergeFrom(const GachaInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GachaInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto.GachaUpInfo gacha_up_info_list = 1233;
  int gacha_up_info_list_size() const;
  void clear_gacha_up_info_list();
  static const int kGachaUpInfoListFieldNumber = 1233;
  const ::proto::GachaUpInfo& gacha_up_info_list(int index) const;
  ::proto::GachaUpInfo* mutable_gacha_up_info_list(int index);
  ::proto::GachaUpInfo* add_gacha_up_info_list();
  ::google::protobuf::RepeatedPtrField< ::proto::GachaUpInfo >*
      mutable_gacha_up_info_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::GachaUpInfo >&
      gacha_up_info_list() const;

  // repeated uint32 display_up4_item_list = 1875;
  int display_up4_item_list_size() const;
  void clear_display_up4_item_list();
  static const int kDisplayUp4ItemListFieldNumber = 1875;
  ::google::protobuf::uint32 display_up4_item_list(int index) const;
  void set_display_up4_item_list(int index, ::google::protobuf::uint32 value);
  void add_display_up4_item_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      display_up4_item_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_display_up4_item_list();

  // repeated uint32 display_up5_item_list = 2006;
  int display_up5_item_list_size() const;
  void clear_display_up5_item_list();
  static const int kDisplayUp5ItemListFieldNumber = 2006;
  ::google::protobuf::uint32 display_up5_item_list(int index) const;
  void set_display_up5_item_list(int index, ::google::protobuf::uint32 value);
  void add_display_up5_item_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      display_up5_item_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_display_up5_item_list();

  // string gacha_preview_prefab_path = 4;
  void clear_gacha_preview_prefab_path();
  static const int kGachaPreviewPrefabPathFieldNumber = 4;
  const ::std::string& gacha_preview_prefab_path() const;
  void set_gacha_preview_prefab_path(const ::std::string& value);
  #if LANG_CXX11
  void set_gacha_preview_prefab_path(::std::string&& value);
  #endif
  void set_gacha_preview_prefab_path(const char* value);
  void set_gacha_preview_prefab_path(const char* value, size_t size);
  ::std::string* mutable_gacha_preview_prefab_path();
  ::std::string* release_gacha_preview_prefab_path();
  void set_allocated_gacha_preview_prefab_path(::std::string* gacha_preview_prefab_path);

  // string gacha_prob_url = 8;
  void clear_gacha_prob_url();
  static const int kGachaProbUrlFieldNumber = 8;
  const ::std::string& gacha_prob_url() const;
  void set_gacha_prob_url(const ::std::string& value);
  #if LANG_CXX11
  void set_gacha_prob_url(::std::string&& value);
  #endif
  void set_gacha_prob_url(const char* value);
  void set_gacha_prob_url(const char* value, size_t size);
  ::std::string* mutable_gacha_prob_url();
  ::std::string* release_gacha_prob_url();
  void set_allocated_gacha_prob_url(::std::string* gacha_prob_url);

  // string gacha_record_url = 12;
  void clear_gacha_record_url();
  static const int kGachaRecordUrlFieldNumber = 12;
  const ::std::string& gacha_record_url() const;
  void set_gacha_record_url(const ::std::string& value);
  #if LANG_CXX11
  void set_gacha_record_url(::std::string&& value);
  #endif
  void set_gacha_record_url(const char* value);
  void set_gacha_record_url(const char* value, size_t size);
  ::std::string* mutable_gacha_record_url();
  ::std::string* release_gacha_record_url();
  void set_allocated_gacha_record_url(::std::string* gacha_record_url);

  // string gacha_prefab_path = 15;
  void clear_gacha_prefab_path();
  static const int kGachaPrefabPathFieldNumber = 15;
  const ::std::string& gacha_prefab_path() const;
  void set_gacha_prefab_path(const ::std::string& value);
  #if LANG_CXX11
  void set_gacha_prefab_path(::std::string&& value);
  #endif
  void set_gacha_prefab_path(const char* value);
  void set_gacha_prefab_path(const char* value, size_t size);
  ::std::string* mutable_gacha_prefab_path();
  ::std::string* release_gacha_prefab_path();
  void set_allocated_gacha_prefab_path(::std::string* gacha_prefab_path);

  // string title_textmap = 736;
  void clear_title_textmap();
  static const int kTitleTextmapFieldNumber = 736;
  const ::std::string& title_textmap() const;
  void set_title_textmap(const ::std::string& value);
  #if LANG_CXX11
  void set_title_textmap(::std::string&& value);
  #endif
  void set_title_textmap(const char* value);
  void set_title_textmap(const char* value, size_t size);
  ::std::string* mutable_title_textmap();
  ::std::string* release_title_textmap();
  void set_allocated_title_textmap(::std::string* title_textmap);

  // string gacha_prob_url_oversea = 1481;
  void clear_gacha_prob_url_oversea();
  static const int kGachaProbUrlOverseaFieldNumber = 1481;
  const ::std::string& gacha_prob_url_oversea() const;
  void set_gacha_prob_url_oversea(const ::std::string& value);
  #if LANG_CXX11
  void set_gacha_prob_url_oversea(::std::string&& value);
  #endif
  void set_gacha_prob_url_oversea(const char* value);
  void set_gacha_prob_url_oversea(const char* value, size_t size);
  ::std::string* mutable_gacha_prob_url_oversea();
  ::std::string* release_gacha_prob_url_oversea();
  void set_allocated_gacha_prob_url_oversea(::std::string* gacha_prob_url_oversea);

  // string gacha_record_url_oversea = 1854;
  void clear_gacha_record_url_oversea();
  static const int kGachaRecordUrlOverseaFieldNumber = 1854;
  const ::std::string& gacha_record_url_oversea() const;
  void set_gacha_record_url_oversea(const ::std::string& value);
  #if LANG_CXX11
  void set_gacha_record_url_oversea(::std::string&& value);
  #endif
  void set_gacha_record_url_oversea(const char* value);
  void set_gacha_record_url_oversea(const char* value, size_t size);
  ::std::string* mutable_gacha_record_url_oversea();
  ::std::string* release_gacha_record_url_oversea();
  void set_allocated_gacha_record_url_oversea(::std::string* gacha_record_url_oversea);

  // uint32 begin_time = 1;
  void clear_begin_time();
  static const int kBeginTimeFieldNumber = 1;
  ::google::protobuf::uint32 begin_time() const;
  void set_begin_time(::google::protobuf::uint32 value);

  // uint32 ten_cost_item_id = 2;
  void clear_ten_cost_item_id();
  static const int kTenCostItemIdFieldNumber = 2;
  ::google::protobuf::uint32 ten_cost_item_id() const;
  void set_ten_cost_item_id(::google::protobuf::uint32 value);

  // uint32 cost_item_num = 3;
  void clear_cost_item_num();
  static const int kCostItemNumFieldNumber = 3;
  ::google::protobuf::uint32 cost_item_num() const;
  void set_cost_item_num(::google::protobuf::uint32 value);

  // uint32 left_gacha_times = 5;
  void clear_left_gacha_times();
  static const int kLeftGachaTimesFieldNumber = 5;
  ::google::protobuf::uint32 left_gacha_times() const;
  void set_left_gacha_times(::google::protobuf::uint32 value);

  // uint32 ten_cost_item_num = 6;
  void clear_ten_cost_item_num();
  static const int kTenCostItemNumFieldNumber = 6;
  ::google::protobuf::uint32 ten_cost_item_num() const;
  void set_ten_cost_item_num(::google::protobuf::uint32 value);

  // uint32 gacha_sort_id = 7;
  void clear_gacha_sort_id();
  static const int kGachaSortIdFieldNumber = 7;
  ::google::protobuf::uint32 gacha_sort_id() const;
  void set_gacha_sort_id(::google::protobuf::uint32 value);

  // uint32 cost_item_id = 9;
  void clear_cost_item_id();
  static const int kCostItemIdFieldNumber = 9;
  ::google::protobuf::uint32 cost_item_id() const;
  void set_cost_item_id(::google::protobuf::uint32 value);

  // uint32 schedule_id = 10;
  void clear_schedule_id();
  static const int kScheduleIdFieldNumber = 10;
  ::google::protobuf::uint32 schedule_id() const;
  void set_schedule_id(::google::protobuf::uint32 value);

  // uint32 gacha_times_limit = 11;
  void clear_gacha_times_limit();
  static const int kGachaTimesLimitFieldNumber = 11;
  ::google::protobuf::uint32 gacha_times_limit() const;
  void set_gacha_times_limit(::google::protobuf::uint32 value);

  // uint32 gacha_type = 13;
  void clear_gacha_type();
  static const int kGachaTypeFieldNumber = 13;
  ::google::protobuf::uint32 gacha_type() const;
  void set_gacha_type(::google::protobuf::uint32 value);

  // uint32 end_time = 14;
  void clear_end_time();
  static const int kEndTimeFieldNumber = 14;
  ::google::protobuf::uint32 end_time() const;
  void set_end_time(::google::protobuf::uint32 value);

  // uint32 cur_schedule_daily_gacha_times = 469;
  void clear_cur_schedule_daily_gacha_times();
  static const int kCurScheduleDailyGachaTimesFieldNumber = 469;
  ::google::protobuf::uint32 cur_schedule_daily_gacha_times() const;
  void set_cur_schedule_daily_gacha_times(::google::protobuf::uint32 value);

  // bool is_new_wish = 733;
  void clear_is_new_wish();
  static const int kIsNewWishFieldNumber = 733;
  bool is_new_wish() const;
  void set_is_new_wish(bool value);

  // uint32 wish_max_progress = 1222;
  void clear_wish_max_progress();
  static const int kWishMaxProgressFieldNumber = 1222;
  ::google::protobuf::uint32 wish_max_progress() const;
  void set_wish_max_progress(::google::protobuf::uint32 value);

  // uint32 wish_item_id = 1637;
  void clear_wish_item_id();
  static const int kWishItemIdFieldNumber = 1637;
  ::google::protobuf::uint32 wish_item_id() const;
  void set_wish_item_id(::google::protobuf::uint32 value);

  // uint32 wish_progress = 1819;
  void clear_wish_progress();
  static const int kWishProgressFieldNumber = 1819;
  ::google::protobuf::uint32 wish_progress() const;
  void set_wish_progress(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.GachaInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::GachaUpInfo > gacha_up_info_list_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > display_up4_item_list_;
  mutable int _display_up4_item_list_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > display_up5_item_list_;
  mutable int _display_up5_item_list_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr gacha_preview_prefab_path_;
  ::google::protobuf::internal::ArenaStringPtr gacha_prob_url_;
  ::google::protobuf::internal::ArenaStringPtr gacha_record_url_;
  ::google::protobuf::internal::ArenaStringPtr gacha_prefab_path_;
  ::google::protobuf::internal::ArenaStringPtr title_textmap_;
  ::google::protobuf::internal::ArenaStringPtr gacha_prob_url_oversea_;
  ::google::protobuf::internal::ArenaStringPtr gacha_record_url_oversea_;
  ::google::protobuf::uint32 begin_time_;
  ::google::protobuf::uint32 ten_cost_item_id_;
  ::google::protobuf::uint32 cost_item_num_;
  ::google::protobuf::uint32 left_gacha_times_;
  ::google::protobuf::uint32 ten_cost_item_num_;
  ::google::protobuf::uint32 gacha_sort_id_;
  ::google::protobuf::uint32 cost_item_id_;
  ::google::protobuf::uint32 schedule_id_;
  ::google::protobuf::uint32 gacha_times_limit_;
  ::google::protobuf::uint32 gacha_type_;
  ::google::protobuf::uint32 end_time_;
  ::google::protobuf::uint32 cur_schedule_daily_gacha_times_;
  bool is_new_wish_;
  ::google::protobuf::uint32 wish_max_progress_;
  ::google::protobuf::uint32 wish_item_id_;
  ::google::protobuf::uint32 wish_progress_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fgacha_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetGachaInfoRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GetGachaInfoRsp) */ {
 public:
  GetGachaInfoRsp();
  virtual ~GetGachaInfoRsp();

  GetGachaInfoRsp(const GetGachaInfoRsp& from);

  inline GetGachaInfoRsp& operator=(const GetGachaInfoRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetGachaInfoRsp(GetGachaInfoRsp&& from) noexcept
    : GetGachaInfoRsp() {
    *this = ::std::move(from);
  }

  inline GetGachaInfoRsp& operator=(GetGachaInfoRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetGachaInfoRsp& default_instance();

  static inline const GetGachaInfoRsp* internal_default_instance() {
    return reinterpret_cast<const GetGachaInfoRsp*>(
               &_GetGachaInfoRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(GetGachaInfoRsp* other);
  friend void swap(GetGachaInfoRsp& a, GetGachaInfoRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetGachaInfoRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  GetGachaInfoRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetGachaInfoRsp& from);
  void MergeFrom(const GetGachaInfoRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetGachaInfoRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GetGachaInfoRsp_CmdId CmdId;
  static const CmdId NONE =
    GetGachaInfoRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    GetGachaInfoRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    GetGachaInfoRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    GetGachaInfoRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return GetGachaInfoRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    GetGachaInfoRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    GetGachaInfoRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    GetGachaInfoRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return GetGachaInfoRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return GetGachaInfoRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return GetGachaInfoRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .proto.GachaInfo gacha_info_list = 13;
  int gacha_info_list_size() const;
  void clear_gacha_info_list();
  static const int kGachaInfoListFieldNumber = 13;
  const ::proto::GachaInfo& gacha_info_list(int index) const;
  ::proto::GachaInfo* mutable_gacha_info_list(int index);
  ::proto::GachaInfo* add_gacha_info_list();
  ::google::protobuf::RepeatedPtrField< ::proto::GachaInfo >*
      mutable_gacha_info_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::GachaInfo >&
      gacha_info_list() const;

  // bool is_under_general_restrict = 6;
  void clear_is_under_general_restrict();
  static const int kIsUnderGeneralRestrictFieldNumber = 6;
  bool is_under_general_restrict() const;
  void set_is_under_general_restrict(bool value);

  // bool is_under_minors_restrict = 2;
  void clear_is_under_minors_restrict();
  static const int kIsUnderMinorsRestrictFieldNumber = 2;
  bool is_under_minors_restrict() const;
  void set_is_under_minors_restrict(bool value);

  // uint32 daily_gacha_times = 5;
  void clear_daily_gacha_times();
  static const int kDailyGachaTimesFieldNumber = 5;
  ::google::protobuf::uint32 daily_gacha_times() const;
  void set_daily_gacha_times(::google::protobuf::uint32 value);

  // uint32 gacha_random = 9;
  void clear_gacha_random();
  static const int kGachaRandomFieldNumber = 9;
  ::google::protobuf::uint32 gacha_random() const;
  void set_gacha_random(::google::protobuf::uint32 value);

  // int32 retcode = 10;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 10;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.GetGachaInfoRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::GachaInfo > gacha_info_list_;
  bool is_under_general_restrict_;
  bool is_under_minors_restrict_;
  ::google::protobuf::uint32 daily_gacha_times_;
  ::google::protobuf::uint32 gacha_random_;
  ::google::protobuf::int32 retcode_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fgacha_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DoGachaReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.DoGachaReq) */ {
 public:
  DoGachaReq();
  virtual ~DoGachaReq();

  DoGachaReq(const DoGachaReq& from);

  inline DoGachaReq& operator=(const DoGachaReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DoGachaReq(DoGachaReq&& from) noexcept
    : DoGachaReq() {
    *this = ::std::move(from);
  }

  inline DoGachaReq& operator=(DoGachaReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DoGachaReq& default_instance();

  static inline const DoGachaReq* internal_default_instance() {
    return reinterpret_cast<const DoGachaReq*>(
               &_DoGachaReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(DoGachaReq* other);
  friend void swap(DoGachaReq& a, DoGachaReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DoGachaReq* New() const PROTOBUF_FINAL { return New(NULL); }

  DoGachaReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DoGachaReq& from);
  void MergeFrom(const DoGachaReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DoGachaReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef DoGachaReq_CmdId CmdId;
  static const CmdId NONE =
    DoGachaReq_CmdId_NONE;
  static const CmdId CMD_ID =
    DoGachaReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    DoGachaReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    DoGachaReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    DoGachaReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return DoGachaReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    DoGachaReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    DoGachaReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    DoGachaReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return DoGachaReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return DoGachaReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return DoGachaReq_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // string gacha_tag = 4;
  void clear_gacha_tag();
  static const int kGachaTagFieldNumber = 4;
  const ::std::string& gacha_tag() const;
  void set_gacha_tag(const ::std::string& value);
  #if LANG_CXX11
  void set_gacha_tag(::std::string&& value);
  #endif
  void set_gacha_tag(const char* value);
  void set_gacha_tag(const char* value, size_t size);
  ::std::string* mutable_gacha_tag();
  ::std::string* release_gacha_tag();
  void set_allocated_gacha_tag(::std::string* gacha_tag);

  // uint32 gacha_schedule_id = 7;
  void clear_gacha_schedule_id();
  static const int kGachaScheduleIdFieldNumber = 7;
  ::google::protobuf::uint32 gacha_schedule_id() const;
  void set_gacha_schedule_id(::google::protobuf::uint32 value);

  // uint32 gacha_times = 10;
  void clear_gacha_times();
  static const int kGachaTimesFieldNumber = 10;
  ::google::protobuf::uint32 gacha_times() const;
  void set_gacha_times(::google::protobuf::uint32 value);

  // uint32 gacha_random = 13;
  void clear_gacha_random();
  static const int kGachaRandomFieldNumber = 13;
  ::google::protobuf::uint32 gacha_random() const;
  void set_gacha_random(::google::protobuf::uint32 value);

  // uint32 gacha_type = 14;
  void clear_gacha_type();
  static const int kGachaTypeFieldNumber = 14;
  ::google::protobuf::uint32 gacha_type() const;
  void set_gacha_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.DoGachaReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr gacha_tag_;
  ::google::protobuf::uint32 gacha_schedule_id_;
  ::google::protobuf::uint32 gacha_times_;
  ::google::protobuf::uint32 gacha_random_;
  ::google::protobuf::uint32 gacha_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fgacha_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GachaTransferItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GachaTransferItem) */ {
 public:
  GachaTransferItem();
  virtual ~GachaTransferItem();

  GachaTransferItem(const GachaTransferItem& from);

  inline GachaTransferItem& operator=(const GachaTransferItem& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GachaTransferItem(GachaTransferItem&& from) noexcept
    : GachaTransferItem() {
    *this = ::std::move(from);
  }

  inline GachaTransferItem& operator=(GachaTransferItem&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GachaTransferItem& default_instance();

  static inline const GachaTransferItem* internal_default_instance() {
    return reinterpret_cast<const GachaTransferItem*>(
               &_GachaTransferItem_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(GachaTransferItem* other);
  friend void swap(GachaTransferItem& a, GachaTransferItem& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GachaTransferItem* New() const PROTOBUF_FINAL { return New(NULL); }

  GachaTransferItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GachaTransferItem& from);
  void MergeFrom(const GachaTransferItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GachaTransferItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .proto.ItemParam item = 3;
  bool has_item() const;
  void clear_item();
  static const int kItemFieldNumber = 3;
  const ::proto::ItemParam& item() const;
  ::proto::ItemParam* mutable_item();
  ::proto::ItemParam* release_item();
  void set_allocated_item(::proto::ItemParam* item);

  // bool is_transfer_item_new = 1;
  void clear_is_transfer_item_new();
  static const int kIsTransferItemNewFieldNumber = 1;
  bool is_transfer_item_new() const;
  void set_is_transfer_item_new(bool value);

  // @@protoc_insertion_point(class_scope:proto.GachaTransferItem)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::proto::ItemParam* item_;
  bool is_transfer_item_new_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fgacha_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GachaItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GachaItem) */ {
 public:
  GachaItem();
  virtual ~GachaItem();

  GachaItem(const GachaItem& from);

  inline GachaItem& operator=(const GachaItem& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GachaItem(GachaItem&& from) noexcept
    : GachaItem() {
    *this = ::std::move(from);
  }

  inline GachaItem& operator=(GachaItem&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GachaItem& default_instance();

  static inline const GachaItem* internal_default_instance() {
    return reinterpret_cast<const GachaItem*>(
               &_GachaItem_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(GachaItem* other);
  friend void swap(GachaItem& a, GachaItem& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GachaItem* New() const PROTOBUF_FINAL { return New(NULL); }

  GachaItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GachaItem& from);
  void MergeFrom(const GachaItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GachaItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto.ItemParam token_item_list = 9;
  int token_item_list_size() const;
  void clear_token_item_list();
  static const int kTokenItemListFieldNumber = 9;
  const ::proto::ItemParam& token_item_list(int index) const;
  ::proto::ItemParam* mutable_token_item_list(int index);
  ::proto::ItemParam* add_token_item_list();
  ::google::protobuf::RepeatedPtrField< ::proto::ItemParam >*
      mutable_token_item_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::ItemParam >&
      token_item_list() const;

  // repeated .proto.GachaTransferItem transfer_items = 12;
  int transfer_items_size() const;
  void clear_transfer_items();
  static const int kTransferItemsFieldNumber = 12;
  const ::proto::GachaTransferItem& transfer_items(int index) const;
  ::proto::GachaTransferItem* mutable_transfer_items(int index);
  ::proto::GachaTransferItem* add_transfer_items();
  ::google::protobuf::RepeatedPtrField< ::proto::GachaTransferItem >*
      mutable_transfer_items();
  const ::google::protobuf::RepeatedPtrField< ::proto::GachaTransferItem >&
      transfer_items() const;

  // .proto.ItemParam gacha_item = 7;
  bool has_gacha_item() const;
  void clear_gacha_item();
  static const int kGachaItemFieldNumber = 7;
  const ::proto::ItemParam& gacha_item() const;
  ::proto::ItemParam* mutable_gacha_item();
  ::proto::ItemParam* release_gacha_item();
  void set_allocated_gacha_item(::proto::ItemParam* gacha_item);

  // bool is_gacha_item_new = 6;
  void clear_is_gacha_item_new();
  static const int kIsGachaItemNewFieldNumber = 6;
  bool is_gacha_item_new() const;
  void set_is_gacha_item_new(bool value);

  // bool is_flash_card = 8;
  void clear_is_flash_card();
  static const int kIsFlashCardFieldNumber = 8;
  bool is_flash_card() const;
  void set_is_flash_card(bool value);

  // @@protoc_insertion_point(class_scope:proto.GachaItem)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::ItemParam > token_item_list_;
  ::google::protobuf::RepeatedPtrField< ::proto::GachaTransferItem > transfer_items_;
  ::proto::ItemParam* gacha_item_;
  bool is_gacha_item_new_;
  bool is_flash_card_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fgacha_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DoGachaRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.DoGachaRsp) */ {
 public:
  DoGachaRsp();
  virtual ~DoGachaRsp();

  DoGachaRsp(const DoGachaRsp& from);

  inline DoGachaRsp& operator=(const DoGachaRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DoGachaRsp(DoGachaRsp&& from) noexcept
    : DoGachaRsp() {
    *this = ::std::move(from);
  }

  inline DoGachaRsp& operator=(DoGachaRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DoGachaRsp& default_instance();

  static inline const DoGachaRsp* internal_default_instance() {
    return reinterpret_cast<const DoGachaRsp*>(
               &_DoGachaRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(DoGachaRsp* other);
  friend void swap(DoGachaRsp& a, DoGachaRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DoGachaRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  DoGachaRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DoGachaRsp& from);
  void MergeFrom(const DoGachaRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DoGachaRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef DoGachaRsp_CmdId CmdId;
  static const CmdId NONE =
    DoGachaRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    DoGachaRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    DoGachaRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    DoGachaRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return DoGachaRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    DoGachaRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    DoGachaRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    DoGachaRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return DoGachaRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return DoGachaRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return DoGachaRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .proto.GachaItem gacha_item_list = 15;
  int gacha_item_list_size() const;
  void clear_gacha_item_list();
  static const int kGachaItemListFieldNumber = 15;
  const ::proto::GachaItem& gacha_item_list(int index) const;
  ::proto::GachaItem* mutable_gacha_item_list(int index);
  ::proto::GachaItem* add_gacha_item_list();
  ::google::protobuf::RepeatedPtrField< ::proto::GachaItem >*
      mutable_gacha_item_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::GachaItem >&
      gacha_item_list() const;

  // uint32 gacha_times_limit = 1;
  void clear_gacha_times_limit();
  static const int kGachaTimesLimitFieldNumber = 1;
  ::google::protobuf::uint32 gacha_times_limit() const;
  void set_gacha_times_limit(::google::protobuf::uint32 value);

  // uint32 wish_progress = 2;
  void clear_wish_progress();
  static const int kWishProgressFieldNumber = 2;
  ::google::protobuf::uint32 wish_progress() const;
  void set_wish_progress(::google::protobuf::uint32 value);

  // uint32 ten_cost_item_num = 3;
  void clear_ten_cost_item_num();
  static const int kTenCostItemNumFieldNumber = 3;
  ::google::protobuf::uint32 ten_cost_item_num() const;
  void set_ten_cost_item_num(::google::protobuf::uint32 value);

  // uint32 gacha_times = 4;
  void clear_gacha_times();
  static const int kGachaTimesFieldNumber = 4;
  ::google::protobuf::uint32 gacha_times() const;
  void set_gacha_times(::google::protobuf::uint32 value);

  // uint32 gacha_schedule_id = 5;
  void clear_gacha_schedule_id();
  static const int kGachaScheduleIdFieldNumber = 5;
  ::google::protobuf::uint32 gacha_schedule_id() const;
  void set_gacha_schedule_id(::google::protobuf::uint32 value);

  // uint32 left_gacha_times = 6;
  void clear_left_gacha_times();
  static const int kLeftGachaTimesFieldNumber = 6;
  ::google::protobuf::uint32 left_gacha_times() const;
  void set_left_gacha_times(::google::protobuf::uint32 value);

  // uint32 ten_cost_item_id = 7;
  void clear_ten_cost_item_id();
  static const int kTenCostItemIdFieldNumber = 7;
  ::google::protobuf::uint32 ten_cost_item_id() const;
  void set_ten_cost_item_id(::google::protobuf::uint32 value);

  // uint32 wish_item_id = 8;
  void clear_wish_item_id();
  static const int kWishItemIdFieldNumber = 8;
  ::google::protobuf::uint32 wish_item_id() const;
  void set_wish_item_id(::google::protobuf::uint32 value);

  // uint32 wish_max_progress = 9;
  void clear_wish_max_progress();
  static const int kWishMaxProgressFieldNumber = 9;
  ::google::protobuf::uint32 wish_max_progress() const;
  void set_wish_max_progress(::google::protobuf::uint32 value);

  // uint32 cost_item_num = 10;
  void clear_cost_item_num();
  static const int kCostItemNumFieldNumber = 10;
  ::google::protobuf::uint32 cost_item_num() const;
  void set_cost_item_num(::google::protobuf::uint32 value);

  // uint32 new_gacha_random = 11;
  void clear_new_gacha_random();
  static const int kNewGachaRandomFieldNumber = 11;
  ::google::protobuf::uint32 new_gacha_random() const;
  void set_new_gacha_random(::google::protobuf::uint32 value);

  // uint32 gacha_type = 12;
  void clear_gacha_type();
  static const int kGachaTypeFieldNumber = 12;
  ::google::protobuf::uint32 gacha_type() const;
  void set_gacha_type(::google::protobuf::uint32 value);

  // int32 retcode = 13;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 13;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // uint32 cost_item_id = 14;
  void clear_cost_item_id();
  static const int kCostItemIdFieldNumber = 14;
  ::google::protobuf::uint32 cost_item_id() const;
  void set_cost_item_id(::google::protobuf::uint32 value);

  // bool is_under_minors_restrict = 1435;
  void clear_is_under_minors_restrict();
  static const int kIsUnderMinorsRestrictFieldNumber = 1435;
  bool is_under_minors_restrict() const;
  void set_is_under_minors_restrict(bool value);

  // bool is_under_general_restrict = 1868;
  void clear_is_under_general_restrict();
  static const int kIsUnderGeneralRestrictFieldNumber = 1868;
  bool is_under_general_restrict() const;
  void set_is_under_general_restrict(bool value);

  // uint32 cur_schedule_daily_gacha_times = 155;
  void clear_cur_schedule_daily_gacha_times();
  static const int kCurScheduleDailyGachaTimesFieldNumber = 155;
  ::google::protobuf::uint32 cur_schedule_daily_gacha_times() const;
  void set_cur_schedule_daily_gacha_times(::google::protobuf::uint32 value);

  // uint32 daily_gacha_times = 1240;
  void clear_daily_gacha_times();
  static const int kDailyGachaTimesFieldNumber = 1240;
  ::google::protobuf::uint32 daily_gacha_times() const;
  void set_daily_gacha_times(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.DoGachaRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::GachaItem > gacha_item_list_;
  ::google::protobuf::uint32 gacha_times_limit_;
  ::google::protobuf::uint32 wish_progress_;
  ::google::protobuf::uint32 ten_cost_item_num_;
  ::google::protobuf::uint32 gacha_times_;
  ::google::protobuf::uint32 gacha_schedule_id_;
  ::google::protobuf::uint32 left_gacha_times_;
  ::google::protobuf::uint32 ten_cost_item_id_;
  ::google::protobuf::uint32 wish_item_id_;
  ::google::protobuf::uint32 wish_max_progress_;
  ::google::protobuf::uint32 cost_item_num_;
  ::google::protobuf::uint32 new_gacha_random_;
  ::google::protobuf::uint32 gacha_type_;
  ::google::protobuf::int32 retcode_;
  ::google::protobuf::uint32 cost_item_id_;
  bool is_under_minors_restrict_;
  bool is_under_general_restrict_;
  ::google::protobuf::uint32 cur_schedule_daily_gacha_times_;
  ::google::protobuf::uint32 daily_gacha_times_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fgacha_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GachaWishReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GachaWishReq) */ {
 public:
  GachaWishReq();
  virtual ~GachaWishReq();

  GachaWishReq(const GachaWishReq& from);

  inline GachaWishReq& operator=(const GachaWishReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GachaWishReq(GachaWishReq&& from) noexcept
    : GachaWishReq() {
    *this = ::std::move(from);
  }

  inline GachaWishReq& operator=(GachaWishReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GachaWishReq& default_instance();

  static inline const GachaWishReq* internal_default_instance() {
    return reinterpret_cast<const GachaWishReq*>(
               &_GachaWishReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(GachaWishReq* other);
  friend void swap(GachaWishReq& a, GachaWishReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GachaWishReq* New() const PROTOBUF_FINAL { return New(NULL); }

  GachaWishReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GachaWishReq& from);
  void MergeFrom(const GachaWishReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GachaWishReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GachaWishReq_CmdId CmdId;
  static const CmdId NONE =
    GachaWishReq_CmdId_NONE;
  static const CmdId CMD_ID =
    GachaWishReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    GachaWishReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    GachaWishReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    GachaWishReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return GachaWishReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    GachaWishReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    GachaWishReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    GachaWishReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return GachaWishReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return GachaWishReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return GachaWishReq_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // uint32 gacha_schedule_id = 14;
  void clear_gacha_schedule_id();
  static const int kGachaScheduleIdFieldNumber = 14;
  ::google::protobuf::uint32 gacha_schedule_id() const;
  void set_gacha_schedule_id(::google::protobuf::uint32 value);

  // uint32 item_id = 4;
  void clear_item_id();
  static const int kItemIdFieldNumber = 4;
  ::google::protobuf::uint32 item_id() const;
  void set_item_id(::google::protobuf::uint32 value);

  // uint32 gacha_type = 13;
  void clear_gacha_type();
  static const int kGachaTypeFieldNumber = 13;
  ::google::protobuf::uint32 gacha_type() const;
  void set_gacha_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.GachaWishReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 gacha_schedule_id_;
  ::google::protobuf::uint32 item_id_;
  ::google::protobuf::uint32 gacha_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fgacha_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GachaWishRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GachaWishRsp) */ {
 public:
  GachaWishRsp();
  virtual ~GachaWishRsp();

  GachaWishRsp(const GachaWishRsp& from);

  inline GachaWishRsp& operator=(const GachaWishRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GachaWishRsp(GachaWishRsp&& from) noexcept
    : GachaWishRsp() {
    *this = ::std::move(from);
  }

  inline GachaWishRsp& operator=(GachaWishRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GachaWishRsp& default_instance();

  static inline const GachaWishRsp* internal_default_instance() {
    return reinterpret_cast<const GachaWishRsp*>(
               &_GachaWishRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(GachaWishRsp* other);
  friend void swap(GachaWishRsp& a, GachaWishRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GachaWishRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  GachaWishRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GachaWishRsp& from);
  void MergeFrom(const GachaWishRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GachaWishRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GachaWishRsp_CmdId CmdId;
  static const CmdId NONE =
    GachaWishRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    GachaWishRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    GachaWishRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    GachaWishRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return GachaWishRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    GachaWishRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    GachaWishRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    GachaWishRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return GachaWishRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return GachaWishRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return GachaWishRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // uint32 wish_max_progress = 2;
  void clear_wish_max_progress();
  static const int kWishMaxProgressFieldNumber = 2;
  ::google::protobuf::uint32 wish_max_progress() const;
  void set_wish_max_progress(::google::protobuf::uint32 value);

  // uint32 wish_item_id = 3;
  void clear_wish_item_id();
  static const int kWishItemIdFieldNumber = 3;
  ::google::protobuf::uint32 wish_item_id() const;
  void set_wish_item_id(::google::protobuf::uint32 value);

  // uint32 wish_progress = 5;
  void clear_wish_progress();
  static const int kWishProgressFieldNumber = 5;
  ::google::protobuf::uint32 wish_progress() const;
  void set_wish_progress(::google::protobuf::uint32 value);

  // uint32 gacha_schedule_id = 7;
  void clear_gacha_schedule_id();
  static const int kGachaScheduleIdFieldNumber = 7;
  ::google::protobuf::uint32 gacha_schedule_id() const;
  void set_gacha_schedule_id(::google::protobuf::uint32 value);

  // uint32 gacha_type = 8;
  void clear_gacha_type();
  static const int kGachaTypeFieldNumber = 8;
  ::google::protobuf::uint32 gacha_type() const;
  void set_gacha_type(::google::protobuf::uint32 value);

  // int32 retcode = 14;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 14;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.GachaWishRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 wish_max_progress_;
  ::google::protobuf::uint32 wish_item_id_;
  ::google::protobuf::uint32 wish_progress_;
  ::google::protobuf::uint32 gacha_schedule_id_;
  ::google::protobuf::uint32 gacha_type_;
  ::google::protobuf::int32 retcode_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fgacha_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GachaOpenWishNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GachaOpenWishNotify) */ {
 public:
  GachaOpenWishNotify();
  virtual ~GachaOpenWishNotify();

  GachaOpenWishNotify(const GachaOpenWishNotify& from);

  inline GachaOpenWishNotify& operator=(const GachaOpenWishNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GachaOpenWishNotify(GachaOpenWishNotify&& from) noexcept
    : GachaOpenWishNotify() {
    *this = ::std::move(from);
  }

  inline GachaOpenWishNotify& operator=(GachaOpenWishNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GachaOpenWishNotify& default_instance();

  static inline const GachaOpenWishNotify* internal_default_instance() {
    return reinterpret_cast<const GachaOpenWishNotify*>(
               &_GachaOpenWishNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    10;

  void Swap(GachaOpenWishNotify* other);
  friend void swap(GachaOpenWishNotify& a, GachaOpenWishNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GachaOpenWishNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  GachaOpenWishNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GachaOpenWishNotify& from);
  void MergeFrom(const GachaOpenWishNotify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GachaOpenWishNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GachaOpenWishNotify_CmdId CmdId;
  static const CmdId NONE =
    GachaOpenWishNotify_CmdId_NONE;
  static const CmdId CMD_ID =
    GachaOpenWishNotify_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    GachaOpenWishNotify_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    GachaOpenWishNotify_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    GachaOpenWishNotify_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return GachaOpenWishNotify_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    GachaOpenWishNotify_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    GachaOpenWishNotify_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    GachaOpenWishNotify_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return GachaOpenWishNotify_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return GachaOpenWishNotify_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return GachaOpenWishNotify_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // uint32 gacha_type = 2;
  void clear_gacha_type();
  static const int kGachaTypeFieldNumber = 2;
  ::google::protobuf::uint32 gacha_type() const;
  void set_gacha_type(::google::protobuf::uint32 value);

  // uint32 gacha_schedule_id = 9;
  void clear_gacha_schedule_id();
  static const int kGachaScheduleIdFieldNumber = 9;
  ::google::protobuf::uint32 gacha_schedule_id() const;
  void set_gacha_schedule_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.GachaOpenWishNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 gacha_type_;
  ::google::protobuf::uint32 gacha_schedule_id_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fgacha_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GachaSimpleInfoNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GachaSimpleInfoNotify) */ {
 public:
  GachaSimpleInfoNotify();
  virtual ~GachaSimpleInfoNotify();

  GachaSimpleInfoNotify(const GachaSimpleInfoNotify& from);

  inline GachaSimpleInfoNotify& operator=(const GachaSimpleInfoNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GachaSimpleInfoNotify(GachaSimpleInfoNotify&& from) noexcept
    : GachaSimpleInfoNotify() {
    *this = ::std::move(from);
  }

  inline GachaSimpleInfoNotify& operator=(GachaSimpleInfoNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GachaSimpleInfoNotify& default_instance();

  static inline const GachaSimpleInfoNotify* internal_default_instance() {
    return reinterpret_cast<const GachaSimpleInfoNotify*>(
               &_GachaSimpleInfoNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    11;

  void Swap(GachaSimpleInfoNotify* other);
  friend void swap(GachaSimpleInfoNotify& a, GachaSimpleInfoNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GachaSimpleInfoNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  GachaSimpleInfoNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GachaSimpleInfoNotify& from);
  void MergeFrom(const GachaSimpleInfoNotify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GachaSimpleInfoNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GachaSimpleInfoNotify_CmdId CmdId;
  static const CmdId NONE =
    GachaSimpleInfoNotify_CmdId_NONE;
  static const CmdId CMD_ID =
    GachaSimpleInfoNotify_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    GachaSimpleInfoNotify_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    GachaSimpleInfoNotify_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return GachaSimpleInfoNotify_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    GachaSimpleInfoNotify_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    GachaSimpleInfoNotify_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    GachaSimpleInfoNotify_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return GachaSimpleInfoNotify_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return GachaSimpleInfoNotify_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return GachaSimpleInfoNotify_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // bool is_new = 5;
  void clear_is_new();
  static const int kIsNewFieldNumber = 5;
  bool is_new() const;
  void set_is_new(bool value);

  // @@protoc_insertion_point(class_scope:proto.GachaSimpleInfoNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool is_new_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fgacha_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================


// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::proto::GetGachaInfoReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::GetGachaInfoReq_CmdId>() {
  return ::proto::GetGachaInfoReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::GetGachaInfoRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::GetGachaInfoRsp_CmdId>() {
  return ::proto::GetGachaInfoRsp_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::DoGachaReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::DoGachaReq_CmdId>() {
  return ::proto::DoGachaReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::DoGachaRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::DoGachaRsp_CmdId>() {
  return ::proto::DoGachaRsp_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::GachaWishReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::GachaWishReq_CmdId>() {
  return ::proto::GachaWishReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::GachaWishRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::GachaWishRsp_CmdId>() {
  return ::proto::GachaWishRsp_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::GachaOpenWishNotify_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::GachaOpenWishNotify_CmdId>() {
  return ::proto::GachaOpenWishNotify_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::GachaSimpleInfoNotify_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::GachaSimpleInfoNotify_CmdId>() {
  return ::proto::GachaSimpleInfoNotify_CmdId_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cmd_2fcmd_5fgacha_2eproto__INCLUDED
