// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd/cmd_shop.proto

#ifndef PROTOBUF_cmd_2fcmd_5fshop_2eproto__INCLUDED
#define PROTOBUF_cmd_2fcmd_5fshop_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "define.pb.h"
// @@protoc_insertion_point(includes)
namespace proto {
class ActivityShopSheetInfo;
class ActivityShopSheetInfoDefaultTypeInternal;
extern ActivityShopSheetInfoDefaultTypeInternal _ActivityShopSheetInfo_default_instance_;
class BatchBuyGoodsReq;
class BatchBuyGoodsReqDefaultTypeInternal;
extern BatchBuyGoodsReqDefaultTypeInternal _BatchBuyGoodsReq_default_instance_;
class BatchBuyGoodsRsp;
class BatchBuyGoodsRspDefaultTypeInternal;
extern BatchBuyGoodsRspDefaultTypeInternal _BatchBuyGoodsRsp_default_instance_;
class BuyGoodsParam;
class BuyGoodsParamDefaultTypeInternal;
extern BuyGoodsParamDefaultTypeInternal _BuyGoodsParam_default_instance_;
class BuyGoodsReq;
class BuyGoodsReqDefaultTypeInternal;
extern BuyGoodsReqDefaultTypeInternal _BuyGoodsReq_default_instance_;
class BuyGoodsRsp;
class BuyGoodsRspDefaultTypeInternal;
extern BuyGoodsRspDefaultTypeInternal _BuyGoodsRsp_default_instance_;
class GetActivityShopSheetInfoReq;
class GetActivityShopSheetInfoReqDefaultTypeInternal;
extern GetActivityShopSheetInfoReqDefaultTypeInternal _GetActivityShopSheetInfoReq_default_instance_;
class GetActivityShopSheetInfoRsp;
class GetActivityShopSheetInfoRspDefaultTypeInternal;
extern GetActivityShopSheetInfoRspDefaultTypeInternal _GetActivityShopSheetInfoRsp_default_instance_;
class GetShopReq;
class GetShopReqDefaultTypeInternal;
extern GetShopReqDefaultTypeInternal _GetShopReq_default_instance_;
class GetShopRsp;
class GetShopRspDefaultTypeInternal;
extern GetShopRspDefaultTypeInternal _GetShopRsp_default_instance_;
class GetShopmallDataReq;
class GetShopmallDataReqDefaultTypeInternal;
extern GetShopmallDataReqDefaultTypeInternal _GetShopmallDataReq_default_instance_;
class GetShopmallDataRsp;
class GetShopmallDataRspDefaultTypeInternal;
extern GetShopmallDataRspDefaultTypeInternal _GetShopmallDataRsp_default_instance_;
class Shop;
class ShopDefaultTypeInternal;
extern ShopDefaultTypeInternal _Shop_default_instance_;
class ShopGoods;
class ShopGoodsDefaultTypeInternal;
extern ShopGoodsDefaultTypeInternal _ShopGoods_default_instance_;
}  // namespace proto

namespace proto {

namespace protobuf_cmd_2fcmd_5fshop_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cmd_2fcmd_5fshop_2eproto

enum GetShopReq_CmdId {
  GetShopReq_CmdId_NONE = 0,
  GetShopReq_CmdId_CMD_ID = 772,
  GetShopReq_CmdId_ENET_CHANNEL_ID = 0,
  GetShopReq_CmdId_ENET_IS_RELIABLE = 1,
  GetShopReq_CmdId_IS_ALLOW_CLIENT = 1,
  GetShopReq_CmdId_GetShopReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GetShopReq_CmdId_GetShopReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GetShopReq_CmdId_IsValid(int value);
const GetShopReq_CmdId GetShopReq_CmdId_CmdId_MIN = GetShopReq_CmdId_NONE;
const GetShopReq_CmdId GetShopReq_CmdId_CmdId_MAX = GetShopReq_CmdId_CMD_ID;
const int GetShopReq_CmdId_CmdId_ARRAYSIZE = GetShopReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* GetShopReq_CmdId_descriptor();
inline const ::std::string& GetShopReq_CmdId_Name(GetShopReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    GetShopReq_CmdId_descriptor(), value);
}
inline bool GetShopReq_CmdId_Parse(
    const ::std::string& name, GetShopReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GetShopReq_CmdId>(
    GetShopReq_CmdId_descriptor(), name, value);
}
enum GetShopRsp_CmdId {
  GetShopRsp_CmdId_NONE = 0,
  GetShopRsp_CmdId_CMD_ID = 798,
  GetShopRsp_CmdId_ENET_CHANNEL_ID = 0,
  GetShopRsp_CmdId_ENET_IS_RELIABLE = 1,
  GetShopRsp_CmdId_GetShopRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GetShopRsp_CmdId_GetShopRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GetShopRsp_CmdId_IsValid(int value);
const GetShopRsp_CmdId GetShopRsp_CmdId_CmdId_MIN = GetShopRsp_CmdId_NONE;
const GetShopRsp_CmdId GetShopRsp_CmdId_CmdId_MAX = GetShopRsp_CmdId_CMD_ID;
const int GetShopRsp_CmdId_CmdId_ARRAYSIZE = GetShopRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* GetShopRsp_CmdId_descriptor();
inline const ::std::string& GetShopRsp_CmdId_Name(GetShopRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    GetShopRsp_CmdId_descriptor(), value);
}
inline bool GetShopRsp_CmdId_Parse(
    const ::std::string& name, GetShopRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GetShopRsp_CmdId>(
    GetShopRsp_CmdId_descriptor(), name, value);
}
enum BuyGoodsReq_CmdId {
  BuyGoodsReq_CmdId_NONE = 0,
  BuyGoodsReq_CmdId_CMD_ID = 712,
  BuyGoodsReq_CmdId_ENET_CHANNEL_ID = 0,
  BuyGoodsReq_CmdId_ENET_IS_RELIABLE = 1,
  BuyGoodsReq_CmdId_IS_ALLOW_CLIENT = 1,
  BuyGoodsReq_CmdId_BuyGoodsReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  BuyGoodsReq_CmdId_BuyGoodsReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool BuyGoodsReq_CmdId_IsValid(int value);
const BuyGoodsReq_CmdId BuyGoodsReq_CmdId_CmdId_MIN = BuyGoodsReq_CmdId_NONE;
const BuyGoodsReq_CmdId BuyGoodsReq_CmdId_CmdId_MAX = BuyGoodsReq_CmdId_CMD_ID;
const int BuyGoodsReq_CmdId_CmdId_ARRAYSIZE = BuyGoodsReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* BuyGoodsReq_CmdId_descriptor();
inline const ::std::string& BuyGoodsReq_CmdId_Name(BuyGoodsReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    BuyGoodsReq_CmdId_descriptor(), value);
}
inline bool BuyGoodsReq_CmdId_Parse(
    const ::std::string& name, BuyGoodsReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BuyGoodsReq_CmdId>(
    BuyGoodsReq_CmdId_descriptor(), name, value);
}
enum BuyGoodsRsp_CmdId {
  BuyGoodsRsp_CmdId_NONE = 0,
  BuyGoodsRsp_CmdId_CMD_ID = 735,
  BuyGoodsRsp_CmdId_ENET_CHANNEL_ID = 0,
  BuyGoodsRsp_CmdId_ENET_IS_RELIABLE = 1,
  BuyGoodsRsp_CmdId_BuyGoodsRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  BuyGoodsRsp_CmdId_BuyGoodsRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool BuyGoodsRsp_CmdId_IsValid(int value);
const BuyGoodsRsp_CmdId BuyGoodsRsp_CmdId_CmdId_MIN = BuyGoodsRsp_CmdId_NONE;
const BuyGoodsRsp_CmdId BuyGoodsRsp_CmdId_CmdId_MAX = BuyGoodsRsp_CmdId_CMD_ID;
const int BuyGoodsRsp_CmdId_CmdId_ARRAYSIZE = BuyGoodsRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* BuyGoodsRsp_CmdId_descriptor();
inline const ::std::string& BuyGoodsRsp_CmdId_Name(BuyGoodsRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    BuyGoodsRsp_CmdId_descriptor(), value);
}
inline bool BuyGoodsRsp_CmdId_Parse(
    const ::std::string& name, BuyGoodsRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BuyGoodsRsp_CmdId>(
    BuyGoodsRsp_CmdId_descriptor(), name, value);
}
enum GetShopmallDataReq_CmdId {
  GetShopmallDataReq_CmdId_NONE = 0,
  GetShopmallDataReq_CmdId_CMD_ID = 707,
  GetShopmallDataReq_CmdId_ENET_CHANNEL_ID = 0,
  GetShopmallDataReq_CmdId_ENET_IS_RELIABLE = 1,
  GetShopmallDataReq_CmdId_IS_ALLOW_CLIENT = 1,
  GetShopmallDataReq_CmdId_GetShopmallDataReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GetShopmallDataReq_CmdId_GetShopmallDataReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GetShopmallDataReq_CmdId_IsValid(int value);
const GetShopmallDataReq_CmdId GetShopmallDataReq_CmdId_CmdId_MIN = GetShopmallDataReq_CmdId_NONE;
const GetShopmallDataReq_CmdId GetShopmallDataReq_CmdId_CmdId_MAX = GetShopmallDataReq_CmdId_CMD_ID;
const int GetShopmallDataReq_CmdId_CmdId_ARRAYSIZE = GetShopmallDataReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* GetShopmallDataReq_CmdId_descriptor();
inline const ::std::string& GetShopmallDataReq_CmdId_Name(GetShopmallDataReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    GetShopmallDataReq_CmdId_descriptor(), value);
}
inline bool GetShopmallDataReq_CmdId_Parse(
    const ::std::string& name, GetShopmallDataReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GetShopmallDataReq_CmdId>(
    GetShopmallDataReq_CmdId_descriptor(), name, value);
}
enum GetShopmallDataRsp_CmdId {
  GetShopmallDataRsp_CmdId_NONE = 0,
  GetShopmallDataRsp_CmdId_CMD_ID = 721,
  GetShopmallDataRsp_CmdId_ENET_CHANNEL_ID = 0,
  GetShopmallDataRsp_CmdId_ENET_IS_RELIABLE = 1,
  GetShopmallDataRsp_CmdId_GetShopmallDataRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GetShopmallDataRsp_CmdId_GetShopmallDataRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GetShopmallDataRsp_CmdId_IsValid(int value);
const GetShopmallDataRsp_CmdId GetShopmallDataRsp_CmdId_CmdId_MIN = GetShopmallDataRsp_CmdId_NONE;
const GetShopmallDataRsp_CmdId GetShopmallDataRsp_CmdId_CmdId_MAX = GetShopmallDataRsp_CmdId_CMD_ID;
const int GetShopmallDataRsp_CmdId_CmdId_ARRAYSIZE = GetShopmallDataRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* GetShopmallDataRsp_CmdId_descriptor();
inline const ::std::string& GetShopmallDataRsp_CmdId_Name(GetShopmallDataRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    GetShopmallDataRsp_CmdId_descriptor(), value);
}
inline bool GetShopmallDataRsp_CmdId_Parse(
    const ::std::string& name, GetShopmallDataRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GetShopmallDataRsp_CmdId>(
    GetShopmallDataRsp_CmdId_descriptor(), name, value);
}
enum GetActivityShopSheetInfoReq_CmdId {
  GetActivityShopSheetInfoReq_CmdId_NONE = 0,
  GetActivityShopSheetInfoReq_CmdId_CMD_ID = 703,
  GetActivityShopSheetInfoReq_CmdId_ENET_CHANNEL_ID = 0,
  GetActivityShopSheetInfoReq_CmdId_ENET_IS_RELIABLE = 1,
  GetActivityShopSheetInfoReq_CmdId_IS_ALLOW_CLIENT = 1,
  GetActivityShopSheetInfoReq_CmdId_GetActivityShopSheetInfoReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GetActivityShopSheetInfoReq_CmdId_GetActivityShopSheetInfoReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GetActivityShopSheetInfoReq_CmdId_IsValid(int value);
const GetActivityShopSheetInfoReq_CmdId GetActivityShopSheetInfoReq_CmdId_CmdId_MIN = GetActivityShopSheetInfoReq_CmdId_NONE;
const GetActivityShopSheetInfoReq_CmdId GetActivityShopSheetInfoReq_CmdId_CmdId_MAX = GetActivityShopSheetInfoReq_CmdId_CMD_ID;
const int GetActivityShopSheetInfoReq_CmdId_CmdId_ARRAYSIZE = GetActivityShopSheetInfoReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* GetActivityShopSheetInfoReq_CmdId_descriptor();
inline const ::std::string& GetActivityShopSheetInfoReq_CmdId_Name(GetActivityShopSheetInfoReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    GetActivityShopSheetInfoReq_CmdId_descriptor(), value);
}
inline bool GetActivityShopSheetInfoReq_CmdId_Parse(
    const ::std::string& name, GetActivityShopSheetInfoReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GetActivityShopSheetInfoReq_CmdId>(
    GetActivityShopSheetInfoReq_CmdId_descriptor(), name, value);
}
enum GetActivityShopSheetInfoRsp_CmdId {
  GetActivityShopSheetInfoRsp_CmdId_NONE = 0,
  GetActivityShopSheetInfoRsp_CmdId_CMD_ID = 790,
  GetActivityShopSheetInfoRsp_CmdId_ENET_CHANNEL_ID = 0,
  GetActivityShopSheetInfoRsp_CmdId_ENET_IS_RELIABLE = 1,
  GetActivityShopSheetInfoRsp_CmdId_GetActivityShopSheetInfoRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GetActivityShopSheetInfoRsp_CmdId_GetActivityShopSheetInfoRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GetActivityShopSheetInfoRsp_CmdId_IsValid(int value);
const GetActivityShopSheetInfoRsp_CmdId GetActivityShopSheetInfoRsp_CmdId_CmdId_MIN = GetActivityShopSheetInfoRsp_CmdId_NONE;
const GetActivityShopSheetInfoRsp_CmdId GetActivityShopSheetInfoRsp_CmdId_CmdId_MAX = GetActivityShopSheetInfoRsp_CmdId_CMD_ID;
const int GetActivityShopSheetInfoRsp_CmdId_CmdId_ARRAYSIZE = GetActivityShopSheetInfoRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* GetActivityShopSheetInfoRsp_CmdId_descriptor();
inline const ::std::string& GetActivityShopSheetInfoRsp_CmdId_Name(GetActivityShopSheetInfoRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    GetActivityShopSheetInfoRsp_CmdId_descriptor(), value);
}
inline bool GetActivityShopSheetInfoRsp_CmdId_Parse(
    const ::std::string& name, GetActivityShopSheetInfoRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GetActivityShopSheetInfoRsp_CmdId>(
    GetActivityShopSheetInfoRsp_CmdId_descriptor(), name, value);
}
enum BatchBuyGoodsReq_CmdId {
  BatchBuyGoodsReq_CmdId_NONE = 0,
  BatchBuyGoodsReq_CmdId_CMD_ID = 773,
  BatchBuyGoodsReq_CmdId_ENET_CHANNEL_ID = 0,
  BatchBuyGoodsReq_CmdId_ENET_IS_RELIABLE = 1,
  BatchBuyGoodsReq_CmdId_IS_ALLOW_CLIENT = 1,
  BatchBuyGoodsReq_CmdId_BatchBuyGoodsReq_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  BatchBuyGoodsReq_CmdId_BatchBuyGoodsReq_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool BatchBuyGoodsReq_CmdId_IsValid(int value);
const BatchBuyGoodsReq_CmdId BatchBuyGoodsReq_CmdId_CmdId_MIN = BatchBuyGoodsReq_CmdId_NONE;
const BatchBuyGoodsReq_CmdId BatchBuyGoodsReq_CmdId_CmdId_MAX = BatchBuyGoodsReq_CmdId_CMD_ID;
const int BatchBuyGoodsReq_CmdId_CmdId_ARRAYSIZE = BatchBuyGoodsReq_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* BatchBuyGoodsReq_CmdId_descriptor();
inline const ::std::string& BatchBuyGoodsReq_CmdId_Name(BatchBuyGoodsReq_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    BatchBuyGoodsReq_CmdId_descriptor(), value);
}
inline bool BatchBuyGoodsReq_CmdId_Parse(
    const ::std::string& name, BatchBuyGoodsReq_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BatchBuyGoodsReq_CmdId>(
    BatchBuyGoodsReq_CmdId_descriptor(), name, value);
}
enum BatchBuyGoodsRsp_CmdId {
  BatchBuyGoodsRsp_CmdId_NONE = 0,
  BatchBuyGoodsRsp_CmdId_CMD_ID = 799,
  BatchBuyGoodsRsp_CmdId_ENET_CHANNEL_ID = 0,
  BatchBuyGoodsRsp_CmdId_ENET_IS_RELIABLE = 1,
  BatchBuyGoodsRsp_CmdId_BatchBuyGoodsRsp_CmdId_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  BatchBuyGoodsRsp_CmdId_BatchBuyGoodsRsp_CmdId_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool BatchBuyGoodsRsp_CmdId_IsValid(int value);
const BatchBuyGoodsRsp_CmdId BatchBuyGoodsRsp_CmdId_CmdId_MIN = BatchBuyGoodsRsp_CmdId_NONE;
const BatchBuyGoodsRsp_CmdId BatchBuyGoodsRsp_CmdId_CmdId_MAX = BatchBuyGoodsRsp_CmdId_CMD_ID;
const int BatchBuyGoodsRsp_CmdId_CmdId_ARRAYSIZE = BatchBuyGoodsRsp_CmdId_CmdId_MAX + 1;

const ::google::protobuf::EnumDescriptor* BatchBuyGoodsRsp_CmdId_descriptor();
inline const ::std::string& BatchBuyGoodsRsp_CmdId_Name(BatchBuyGoodsRsp_CmdId value) {
  return ::google::protobuf::internal::NameOfEnum(
    BatchBuyGoodsRsp_CmdId_descriptor(), value);
}
inline bool BatchBuyGoodsRsp_CmdId_Parse(
    const ::std::string& name, BatchBuyGoodsRsp_CmdId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BatchBuyGoodsRsp_CmdId>(
    BatchBuyGoodsRsp_CmdId_descriptor(), name, value);
}
enum ShopGoodsDisableType {
  SHOP_GOODS_DISABLE_NONE = 0,
  SHOP_GOODS_DISABLE_TALENT_FULL = 1,
  SHOP_GOODS_DISABLE_FURNITURE_FORMULA_UNLOCKED = 2,
  SHOP_GOODS_DISABLE_COSTUME_UNLOCKED = 3,
  SHOP_GOODS_DISABLE_BGM_UNLOCKED = 4,
  SHOP_GOODS_DISABLE_GCG_CARD_EXCEED = 5,
  SHOP_GOODS_DISABLE_GCG_CARD_FACE_UNLOCKED = 6,
  SHOP_GOODS_DISABLE_GCG_CARD_BACK_UNLOCKED = 7,
  SHOP_GOODS_DISABLE_GCG_FIELD_UNLOCKED = 8,
  ShopGoodsDisableType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ShopGoodsDisableType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ShopGoodsDisableType_IsValid(int value);
const ShopGoodsDisableType ShopGoodsDisableType_MIN = SHOP_GOODS_DISABLE_NONE;
const ShopGoodsDisableType ShopGoodsDisableType_MAX = SHOP_GOODS_DISABLE_GCG_FIELD_UNLOCKED;
const int ShopGoodsDisableType_ARRAYSIZE = ShopGoodsDisableType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ShopGoodsDisableType_descriptor();
inline const ::std::string& ShopGoodsDisableType_Name(ShopGoodsDisableType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ShopGoodsDisableType_descriptor(), value);
}
inline bool ShopGoodsDisableType_Parse(
    const ::std::string& name, ShopGoodsDisableType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ShopGoodsDisableType>(
    ShopGoodsDisableType_descriptor(), name, value);
}
// ===================================================================

class ShopGoods : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.ShopGoods) */ {
 public:
  ShopGoods();
  virtual ~ShopGoods();

  ShopGoods(const ShopGoods& from);

  inline ShopGoods& operator=(const ShopGoods& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ShopGoods(ShopGoods&& from) noexcept
    : ShopGoods() {
    *this = ::std::move(from);
  }

  inline ShopGoods& operator=(ShopGoods&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ShopGoods& default_instance();

  static inline const ShopGoods* internal_default_instance() {
    return reinterpret_cast<const ShopGoods*>(
               &_ShopGoods_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ShopGoods* other);
  friend void swap(ShopGoods& a, ShopGoods& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ShopGoods* New() const PROTOBUF_FINAL { return New(NULL); }

  ShopGoods* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ShopGoods& from);
  void MergeFrom(const ShopGoods& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ShopGoods* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 pre_goods_id_list = 2;
  int pre_goods_id_list_size() const;
  void clear_pre_goods_id_list();
  static const int kPreGoodsIdListFieldNumber = 2;
  ::google::protobuf::uint32 pre_goods_id_list(int index) const;
  void set_pre_goods_id_list(int index, ::google::protobuf::uint32 value);
  void add_pre_goods_id_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      pre_goods_id_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_pre_goods_id_list();

  // repeated .proto.ItemParam cost_item_list = 3;
  int cost_item_list_size() const;
  void clear_cost_item_list();
  static const int kCostItemListFieldNumber = 3;
  const ::proto::ItemParam& cost_item_list(int index) const;
  ::proto::ItemParam* mutable_cost_item_list(int index);
  ::proto::ItemParam* add_cost_item_list();
  ::google::protobuf::RepeatedPtrField< ::proto::ItemParam >*
      mutable_cost_item_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::ItemParam >&
      cost_item_list() const;

  // .proto.ItemParam goods_item = 9;
  bool has_goods_item() const;
  void clear_goods_item();
  static const int kGoodsItemFieldNumber = 9;
  const ::proto::ItemParam& goods_item() const;
  ::proto::ItemParam* mutable_goods_item();
  ::proto::ItemParam* release_goods_item();
  void set_allocated_goods_item(::proto::ItemParam* goods_item);

  // uint32 hcoin = 1;
  void clear_hcoin();
  static const int kHcoinFieldNumber = 1;
  ::google::protobuf::uint32 hcoin() const;
  void set_hcoin(::google::protobuf::uint32 value);

  // uint32 max_level = 4;
  void clear_max_level();
  static const int kMaxLevelFieldNumber = 4;
  ::google::protobuf::uint32 max_level() const;
  void set_max_level(::google::protobuf::uint32 value);

  // uint32 begin_time = 5;
  void clear_begin_time();
  static const int kBeginTimeFieldNumber = 5;
  ::google::protobuf::uint32 begin_time() const;
  void set_begin_time(::google::protobuf::uint32 value);

  // uint32 disable_type = 6;
  void clear_disable_type();
  static const int kDisableTypeFieldNumber = 6;
  ::google::protobuf::uint32 disable_type() const;
  void set_disable_type(::google::protobuf::uint32 value);

  // uint32 next_refresh_time = 7;
  void clear_next_refresh_time();
  static const int kNextRefreshTimeFieldNumber = 7;
  ::google::protobuf::uint32 next_refresh_time() const;
  void set_next_refresh_time(::google::protobuf::uint32 value);

  // uint32 min_level = 8;
  void clear_min_level();
  static const int kMinLevelFieldNumber = 8;
  ::google::protobuf::uint32 min_level() const;
  void set_min_level(::google::protobuf::uint32 value);

  // uint32 bought_num = 10;
  void clear_bought_num();
  static const int kBoughtNumFieldNumber = 10;
  ::google::protobuf::uint32 bought_num() const;
  void set_bought_num(::google::protobuf::uint32 value);

  // uint32 end_time = 11;
  void clear_end_time();
  static const int kEndTimeFieldNumber = 11;
  ::google::protobuf::uint32 end_time() const;
  void set_end_time(::google::protobuf::uint32 value);

  // uint32 buy_limit = 12;
  void clear_buy_limit();
  static const int kBuyLimitFieldNumber = 12;
  ::google::protobuf::uint32 buy_limit() const;
  void set_buy_limit(::google::protobuf::uint32 value);

  // uint32 goods_id = 13;
  void clear_goods_id();
  static const int kGoodsIdFieldNumber = 13;
  ::google::protobuf::uint32 goods_id() const;
  void set_goods_id(::google::protobuf::uint32 value);

  // uint32 mcoin = 14;
  void clear_mcoin();
  static const int kMcoinFieldNumber = 14;
  ::google::protobuf::uint32 mcoin() const;
  void set_mcoin(::google::protobuf::uint32 value);

  // uint32 scoin = 15;
  void clear_scoin();
  static const int kScoinFieldNumber = 15;
  ::google::protobuf::uint32 scoin() const;
  void set_scoin(::google::protobuf::uint32 value);

  // uint32 discount_id = 1998;
  void clear_discount_id();
  static const int kDiscountIdFieldNumber = 1998;
  ::google::protobuf::uint32 discount_id() const;
  void set_discount_id(::google::protobuf::uint32 value);

  // uint32 single_limit = 247;
  void clear_single_limit();
  static const int kSingleLimitFieldNumber = 247;
  ::google::protobuf::uint32 single_limit() const;
  void set_single_limit(::google::protobuf::uint32 value);

  // uint32 discount_end_time = 258;
  void clear_discount_end_time();
  static const int kDiscountEndTimeFieldNumber = 258;
  ::google::protobuf::uint32 discount_end_time() const;
  void set_discount_end_time(::google::protobuf::uint32 value);

  // uint32 secondary_sheet_id = 318;
  void clear_secondary_sheet_id();
  static const int kSecondarySheetIdFieldNumber = 318;
  ::google::protobuf::uint32 secondary_sheet_id() const;
  void set_secondary_sheet_id(::google::protobuf::uint32 value);

  // uint32 discount_begin_time = 574;
  void clear_discount_begin_time();
  static const int kDiscountBeginTimeFieldNumber = 574;
  ::google::protobuf::uint32 discount_begin_time() const;
  void set_discount_begin_time(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.ShopGoods)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > pre_goods_id_list_;
  mutable int _pre_goods_id_list_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::proto::ItemParam > cost_item_list_;
  ::proto::ItemParam* goods_item_;
  ::google::protobuf::uint32 hcoin_;
  ::google::protobuf::uint32 max_level_;
  ::google::protobuf::uint32 begin_time_;
  ::google::protobuf::uint32 disable_type_;
  ::google::protobuf::uint32 next_refresh_time_;
  ::google::protobuf::uint32 min_level_;
  ::google::protobuf::uint32 bought_num_;
  ::google::protobuf::uint32 end_time_;
  ::google::protobuf::uint32 buy_limit_;
  ::google::protobuf::uint32 goods_id_;
  ::google::protobuf::uint32 mcoin_;
  ::google::protobuf::uint32 scoin_;
  ::google::protobuf::uint32 discount_id_;
  ::google::protobuf::uint32 single_limit_;
  ::google::protobuf::uint32 discount_end_time_;
  ::google::protobuf::uint32 secondary_sheet_id_;
  ::google::protobuf::uint32 discount_begin_time_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Shop : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.Shop) */ {
 public:
  Shop();
  virtual ~Shop();

  Shop(const Shop& from);

  inline Shop& operator=(const Shop& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Shop(Shop&& from) noexcept
    : Shop() {
    *this = ::std::move(from);
  }

  inline Shop& operator=(Shop&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Shop& default_instance();

  static inline const Shop* internal_default_instance() {
    return reinterpret_cast<const Shop*>(
               &_Shop_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Shop* other);
  friend void swap(Shop& a, Shop& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Shop* New() const PROTOBUF_FINAL { return New(NULL); }

  Shop* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Shop& from);
  void MergeFrom(const Shop& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Shop* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto.ShopConcertProduct concert_product_list = 3;
  int concert_product_list_size() const;
  void clear_concert_product_list();
  static const int kConcertProductListFieldNumber = 3;
  const ::proto::ShopConcertProduct& concert_product_list(int index) const;
  ::proto::ShopConcertProduct* mutable_concert_product_list(int index);
  ::proto::ShopConcertProduct* add_concert_product_list();
  ::google::protobuf::RepeatedPtrField< ::proto::ShopConcertProduct >*
      mutable_concert_product_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::ShopConcertProduct >&
      concert_product_list() const;

  // repeated .proto.ShopMcoinProduct mcoin_product_list = 7;
  int mcoin_product_list_size() const;
  void clear_mcoin_product_list();
  static const int kMcoinProductListFieldNumber = 7;
  const ::proto::ShopMcoinProduct& mcoin_product_list(int index) const;
  ::proto::ShopMcoinProduct* mutable_mcoin_product_list(int index);
  ::proto::ShopMcoinProduct* add_mcoin_product_list();
  ::google::protobuf::RepeatedPtrField< ::proto::ShopMcoinProduct >*
      mutable_mcoin_product_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::ShopMcoinProduct >&
      mcoin_product_list() const;

  // repeated .proto.ShopCardProduct card_product_list = 14;
  int card_product_list_size() const;
  void clear_card_product_list();
  static const int kCardProductListFieldNumber = 14;
  const ::proto::ShopCardProduct& card_product_list(int index) const;
  ::proto::ShopCardProduct* mutable_card_product_list(int index);
  ::proto::ShopCardProduct* add_card_product_list();
  ::google::protobuf::RepeatedPtrField< ::proto::ShopCardProduct >*
      mutable_card_product_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::ShopCardProduct >&
      card_product_list() const;

  // repeated .proto.ShopGoods goods_list = 15;
  int goods_list_size() const;
  void clear_goods_list();
  static const int kGoodsListFieldNumber = 15;
  const ::proto::ShopGoods& goods_list(int index) const;
  ::proto::ShopGoods* mutable_goods_list(int index);
  ::proto::ShopGoods* add_goods_list();
  ::google::protobuf::RepeatedPtrField< ::proto::ShopGoods >*
      mutable_goods_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::ShopGoods >&
      goods_list() const;

  // uint32 city_reputation_level = 2;
  void clear_city_reputation_level();
  static const int kCityReputationLevelFieldNumber = 2;
  ::google::protobuf::uint32 city_reputation_level() const;
  void set_city_reputation_level(::google::protobuf::uint32 value);

  // uint32 city_id = 10;
  void clear_city_id();
  static const int kCityIdFieldNumber = 10;
  ::google::protobuf::uint32 city_id() const;
  void set_city_id(::google::protobuf::uint32 value);

  // uint32 next_refresh_time = 11;
  void clear_next_refresh_time();
  static const int kNextRefreshTimeFieldNumber = 11;
  ::google::protobuf::uint32 next_refresh_time() const;
  void set_next_refresh_time(::google::protobuf::uint32 value);

  // uint32 shop_type = 13;
  void clear_shop_type();
  static const int kShopTypeFieldNumber = 13;
  ::google::protobuf::uint32 shop_type() const;
  void set_shop_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.Shop)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::ShopConcertProduct > concert_product_list_;
  ::google::protobuf::RepeatedPtrField< ::proto::ShopMcoinProduct > mcoin_product_list_;
  ::google::protobuf::RepeatedPtrField< ::proto::ShopCardProduct > card_product_list_;
  ::google::protobuf::RepeatedPtrField< ::proto::ShopGoods > goods_list_;
  ::google::protobuf::uint32 city_reputation_level_;
  ::google::protobuf::uint32 city_id_;
  ::google::protobuf::uint32 next_refresh_time_;
  ::google::protobuf::uint32 shop_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetShopReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GetShopReq) */ {
 public:
  GetShopReq();
  virtual ~GetShopReq();

  GetShopReq(const GetShopReq& from);

  inline GetShopReq& operator=(const GetShopReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetShopReq(GetShopReq&& from) noexcept
    : GetShopReq() {
    *this = ::std::move(from);
  }

  inline GetShopReq& operator=(GetShopReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetShopReq& default_instance();

  static inline const GetShopReq* internal_default_instance() {
    return reinterpret_cast<const GetShopReq*>(
               &_GetShopReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(GetShopReq* other);
  friend void swap(GetShopReq& a, GetShopReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetShopReq* New() const PROTOBUF_FINAL { return New(NULL); }

  GetShopReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetShopReq& from);
  void MergeFrom(const GetShopReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetShopReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GetShopReq_CmdId CmdId;
  static const CmdId NONE =
    GetShopReq_CmdId_NONE;
  static const CmdId CMD_ID =
    GetShopReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    GetShopReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    GetShopReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    GetShopReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return GetShopReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    GetShopReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    GetShopReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    GetShopReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return GetShopReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return GetShopReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return GetShopReq_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // uint32 shop_type = 13;
  void clear_shop_type();
  static const int kShopTypeFieldNumber = 13;
  ::google::protobuf::uint32 shop_type() const;
  void set_shop_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.GetShopReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 shop_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetShopRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GetShopRsp) */ {
 public:
  GetShopRsp();
  virtual ~GetShopRsp();

  GetShopRsp(const GetShopRsp& from);

  inline GetShopRsp& operator=(const GetShopRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetShopRsp(GetShopRsp&& from) noexcept
    : GetShopRsp() {
    *this = ::std::move(from);
  }

  inline GetShopRsp& operator=(GetShopRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetShopRsp& default_instance();

  static inline const GetShopRsp* internal_default_instance() {
    return reinterpret_cast<const GetShopRsp*>(
               &_GetShopRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(GetShopRsp* other);
  friend void swap(GetShopRsp& a, GetShopRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetShopRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  GetShopRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetShopRsp& from);
  void MergeFrom(const GetShopRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetShopRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GetShopRsp_CmdId CmdId;
  static const CmdId NONE =
    GetShopRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    GetShopRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    GetShopRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    GetShopRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return GetShopRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    GetShopRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    GetShopRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    GetShopRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return GetShopRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return GetShopRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return GetShopRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .proto.Shop shop = 11;
  bool has_shop() const;
  void clear_shop();
  static const int kShopFieldNumber = 11;
  const ::proto::Shop& shop() const;
  ::proto::Shop* mutable_shop();
  ::proto::Shop* release_shop();
  void set_allocated_shop(::proto::Shop* shop);

  // int32 retcode = 2;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 2;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.GetShopRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::proto::Shop* shop_;
  ::google::protobuf::int32 retcode_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BuyGoodsReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.BuyGoodsReq) */ {
 public:
  BuyGoodsReq();
  virtual ~BuyGoodsReq();

  BuyGoodsReq(const BuyGoodsReq& from);

  inline BuyGoodsReq& operator=(const BuyGoodsReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BuyGoodsReq(BuyGoodsReq&& from) noexcept
    : BuyGoodsReq() {
    *this = ::std::move(from);
  }

  inline BuyGoodsReq& operator=(BuyGoodsReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BuyGoodsReq& default_instance();

  static inline const BuyGoodsReq* internal_default_instance() {
    return reinterpret_cast<const BuyGoodsReq*>(
               &_BuyGoodsReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(BuyGoodsReq* other);
  friend void swap(BuyGoodsReq& a, BuyGoodsReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BuyGoodsReq* New() const PROTOBUF_FINAL { return New(NULL); }

  BuyGoodsReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BuyGoodsReq& from);
  void MergeFrom(const BuyGoodsReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BuyGoodsReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef BuyGoodsReq_CmdId CmdId;
  static const CmdId NONE =
    BuyGoodsReq_CmdId_NONE;
  static const CmdId CMD_ID =
    BuyGoodsReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    BuyGoodsReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    BuyGoodsReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    BuyGoodsReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return BuyGoodsReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    BuyGoodsReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    BuyGoodsReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    BuyGoodsReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return BuyGoodsReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return BuyGoodsReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return BuyGoodsReq_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .proto.ShopGoods goods = 15;
  bool has_goods() const;
  void clear_goods();
  static const int kGoodsFieldNumber = 15;
  const ::proto::ShopGoods& goods() const;
  ::proto::ShopGoods* mutable_goods();
  ::proto::ShopGoods* release_goods();
  void set_allocated_goods(::proto::ShopGoods* goods);

  // uint32 shop_type = 7;
  void clear_shop_type();
  static const int kShopTypeFieldNumber = 7;
  ::google::protobuf::uint32 shop_type() const;
  void set_shop_type(::google::protobuf::uint32 value);

  // uint32 buy_count = 14;
  void clear_buy_count();
  static const int kBuyCountFieldNumber = 14;
  ::google::protobuf::uint32 buy_count() const;
  void set_buy_count(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.BuyGoodsReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::proto::ShopGoods* goods_;
  ::google::protobuf::uint32 shop_type_;
  ::google::protobuf::uint32 buy_count_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BuyGoodsRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.BuyGoodsRsp) */ {
 public:
  BuyGoodsRsp();
  virtual ~BuyGoodsRsp();

  BuyGoodsRsp(const BuyGoodsRsp& from);

  inline BuyGoodsRsp& operator=(const BuyGoodsRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BuyGoodsRsp(BuyGoodsRsp&& from) noexcept
    : BuyGoodsRsp() {
    *this = ::std::move(from);
  }

  inline BuyGoodsRsp& operator=(BuyGoodsRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BuyGoodsRsp& default_instance();

  static inline const BuyGoodsRsp* internal_default_instance() {
    return reinterpret_cast<const BuyGoodsRsp*>(
               &_BuyGoodsRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(BuyGoodsRsp* other);
  friend void swap(BuyGoodsRsp& a, BuyGoodsRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BuyGoodsRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  BuyGoodsRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BuyGoodsRsp& from);
  void MergeFrom(const BuyGoodsRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BuyGoodsRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef BuyGoodsRsp_CmdId CmdId;
  static const CmdId NONE =
    BuyGoodsRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    BuyGoodsRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    BuyGoodsRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    BuyGoodsRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return BuyGoodsRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    BuyGoodsRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    BuyGoodsRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    BuyGoodsRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return BuyGoodsRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return BuyGoodsRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return BuyGoodsRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .proto.ShopGoods goods_list = 5;
  int goods_list_size() const;
  void clear_goods_list();
  static const int kGoodsListFieldNumber = 5;
  const ::proto::ShopGoods& goods_list(int index) const;
  ::proto::ShopGoods* mutable_goods_list(int index);
  ::proto::ShopGoods* add_goods_list();
  ::google::protobuf::RepeatedPtrField< ::proto::ShopGoods >*
      mutable_goods_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::ShopGoods >&
      goods_list() const;

  // .proto.ShopGoods goods = 12;
  bool has_goods() const;
  void clear_goods();
  static const int kGoodsFieldNumber = 12;
  const ::proto::ShopGoods& goods() const;
  ::proto::ShopGoods* mutable_goods();
  ::proto::ShopGoods* release_goods();
  void set_allocated_goods(::proto::ShopGoods* goods);

  // uint32 buy_count = 14;
  void clear_buy_count();
  static const int kBuyCountFieldNumber = 14;
  ::google::protobuf::uint32 buy_count() const;
  void set_buy_count(::google::protobuf::uint32 value);

  // int32 retcode = 2;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 2;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // uint32 shop_type = 11;
  void clear_shop_type();
  static const int kShopTypeFieldNumber = 11;
  ::google::protobuf::uint32 shop_type() const;
  void set_shop_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.BuyGoodsRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::ShopGoods > goods_list_;
  ::proto::ShopGoods* goods_;
  ::google::protobuf::uint32 buy_count_;
  ::google::protobuf::int32 retcode_;
  ::google::protobuf::uint32 shop_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetShopmallDataReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GetShopmallDataReq) */ {
 public:
  GetShopmallDataReq();
  virtual ~GetShopmallDataReq();

  GetShopmallDataReq(const GetShopmallDataReq& from);

  inline GetShopmallDataReq& operator=(const GetShopmallDataReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetShopmallDataReq(GetShopmallDataReq&& from) noexcept
    : GetShopmallDataReq() {
    *this = ::std::move(from);
  }

  inline GetShopmallDataReq& operator=(GetShopmallDataReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetShopmallDataReq& default_instance();

  static inline const GetShopmallDataReq* internal_default_instance() {
    return reinterpret_cast<const GetShopmallDataReq*>(
               &_GetShopmallDataReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(GetShopmallDataReq* other);
  friend void swap(GetShopmallDataReq& a, GetShopmallDataReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetShopmallDataReq* New() const PROTOBUF_FINAL { return New(NULL); }

  GetShopmallDataReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetShopmallDataReq& from);
  void MergeFrom(const GetShopmallDataReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetShopmallDataReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GetShopmallDataReq_CmdId CmdId;
  static const CmdId NONE =
    GetShopmallDataReq_CmdId_NONE;
  static const CmdId CMD_ID =
    GetShopmallDataReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    GetShopmallDataReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    GetShopmallDataReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    GetShopmallDataReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return GetShopmallDataReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    GetShopmallDataReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    GetShopmallDataReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    GetShopmallDataReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return GetShopmallDataReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return GetShopmallDataReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return GetShopmallDataReq_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:proto.GetShopmallDataReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetShopmallDataRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GetShopmallDataRsp) */ {
 public:
  GetShopmallDataRsp();
  virtual ~GetShopmallDataRsp();

  GetShopmallDataRsp(const GetShopmallDataRsp& from);

  inline GetShopmallDataRsp& operator=(const GetShopmallDataRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetShopmallDataRsp(GetShopmallDataRsp&& from) noexcept
    : GetShopmallDataRsp() {
    *this = ::std::move(from);
  }

  inline GetShopmallDataRsp& operator=(GetShopmallDataRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetShopmallDataRsp& default_instance();

  static inline const GetShopmallDataRsp* internal_default_instance() {
    return reinterpret_cast<const GetShopmallDataRsp*>(
               &_GetShopmallDataRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(GetShopmallDataRsp* other);
  friend void swap(GetShopmallDataRsp& a, GetShopmallDataRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetShopmallDataRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  GetShopmallDataRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetShopmallDataRsp& from);
  void MergeFrom(const GetShopmallDataRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetShopmallDataRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GetShopmallDataRsp_CmdId CmdId;
  static const CmdId NONE =
    GetShopmallDataRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    GetShopmallDataRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    GetShopmallDataRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    GetShopmallDataRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return GetShopmallDataRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    GetShopmallDataRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    GetShopmallDataRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    GetShopmallDataRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return GetShopmallDataRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return GetShopmallDataRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return GetShopmallDataRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated uint32 shop_type_list = 15;
  int shop_type_list_size() const;
  void clear_shop_type_list();
  static const int kShopTypeListFieldNumber = 15;
  ::google::protobuf::uint32 shop_type_list(int index) const;
  void set_shop_type_list(int index, ::google::protobuf::uint32 value);
  void add_shop_type_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      shop_type_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_shop_type_list();

  // int32 retcode = 3;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 3;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.GetShopmallDataRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > shop_type_list_;
  mutable int _shop_type_list_cached_byte_size_;
  ::google::protobuf::int32 retcode_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ActivityShopSheetInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.ActivityShopSheetInfo) */ {
 public:
  ActivityShopSheetInfo();
  virtual ~ActivityShopSheetInfo();

  ActivityShopSheetInfo(const ActivityShopSheetInfo& from);

  inline ActivityShopSheetInfo& operator=(const ActivityShopSheetInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ActivityShopSheetInfo(ActivityShopSheetInfo&& from) noexcept
    : ActivityShopSheetInfo() {
    *this = ::std::move(from);
  }

  inline ActivityShopSheetInfo& operator=(ActivityShopSheetInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ActivityShopSheetInfo& default_instance();

  static inline const ActivityShopSheetInfo* internal_default_instance() {
    return reinterpret_cast<const ActivityShopSheetInfo*>(
               &_ActivityShopSheetInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(ActivityShopSheetInfo* other);
  friend void swap(ActivityShopSheetInfo& a, ActivityShopSheetInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ActivityShopSheetInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  ActivityShopSheetInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ActivityShopSheetInfo& from);
  void MergeFrom(const ActivityShopSheetInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ActivityShopSheetInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 end_time = 1;
  void clear_end_time();
  static const int kEndTimeFieldNumber = 1;
  ::google::protobuf::uint32 end_time() const;
  void set_end_time(::google::protobuf::uint32 value);

  // uint32 sheet_id = 2;
  void clear_sheet_id();
  static const int kSheetIdFieldNumber = 2;
  ::google::protobuf::uint32 sheet_id() const;
  void set_sheet_id(::google::protobuf::uint32 value);

  // uint32 begin_time = 12;
  void clear_begin_time();
  static const int kBeginTimeFieldNumber = 12;
  ::google::protobuf::uint32 begin_time() const;
  void set_begin_time(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.ActivityShopSheetInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 end_time_;
  ::google::protobuf::uint32 sheet_id_;
  ::google::protobuf::uint32 begin_time_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetActivityShopSheetInfoReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GetActivityShopSheetInfoReq) */ {
 public:
  GetActivityShopSheetInfoReq();
  virtual ~GetActivityShopSheetInfoReq();

  GetActivityShopSheetInfoReq(const GetActivityShopSheetInfoReq& from);

  inline GetActivityShopSheetInfoReq& operator=(const GetActivityShopSheetInfoReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetActivityShopSheetInfoReq(GetActivityShopSheetInfoReq&& from) noexcept
    : GetActivityShopSheetInfoReq() {
    *this = ::std::move(from);
  }

  inline GetActivityShopSheetInfoReq& operator=(GetActivityShopSheetInfoReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetActivityShopSheetInfoReq& default_instance();

  static inline const GetActivityShopSheetInfoReq* internal_default_instance() {
    return reinterpret_cast<const GetActivityShopSheetInfoReq*>(
               &_GetActivityShopSheetInfoReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(GetActivityShopSheetInfoReq* other);
  friend void swap(GetActivityShopSheetInfoReq& a, GetActivityShopSheetInfoReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetActivityShopSheetInfoReq* New() const PROTOBUF_FINAL { return New(NULL); }

  GetActivityShopSheetInfoReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetActivityShopSheetInfoReq& from);
  void MergeFrom(const GetActivityShopSheetInfoReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetActivityShopSheetInfoReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GetActivityShopSheetInfoReq_CmdId CmdId;
  static const CmdId NONE =
    GetActivityShopSheetInfoReq_CmdId_NONE;
  static const CmdId CMD_ID =
    GetActivityShopSheetInfoReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    GetActivityShopSheetInfoReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    GetActivityShopSheetInfoReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    GetActivityShopSheetInfoReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return GetActivityShopSheetInfoReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    GetActivityShopSheetInfoReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    GetActivityShopSheetInfoReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    GetActivityShopSheetInfoReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return GetActivityShopSheetInfoReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return GetActivityShopSheetInfoReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return GetActivityShopSheetInfoReq_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // uint32 shop_type = 7;
  void clear_shop_type();
  static const int kShopTypeFieldNumber = 7;
  ::google::protobuf::uint32 shop_type() const;
  void set_shop_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.GetActivityShopSheetInfoReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 shop_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetActivityShopSheetInfoRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.GetActivityShopSheetInfoRsp) */ {
 public:
  GetActivityShopSheetInfoRsp();
  virtual ~GetActivityShopSheetInfoRsp();

  GetActivityShopSheetInfoRsp(const GetActivityShopSheetInfoRsp& from);

  inline GetActivityShopSheetInfoRsp& operator=(const GetActivityShopSheetInfoRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetActivityShopSheetInfoRsp(GetActivityShopSheetInfoRsp&& from) noexcept
    : GetActivityShopSheetInfoRsp() {
    *this = ::std::move(from);
  }

  inline GetActivityShopSheetInfoRsp& operator=(GetActivityShopSheetInfoRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetActivityShopSheetInfoRsp& default_instance();

  static inline const GetActivityShopSheetInfoRsp* internal_default_instance() {
    return reinterpret_cast<const GetActivityShopSheetInfoRsp*>(
               &_GetActivityShopSheetInfoRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    10;

  void Swap(GetActivityShopSheetInfoRsp* other);
  friend void swap(GetActivityShopSheetInfoRsp& a, GetActivityShopSheetInfoRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetActivityShopSheetInfoRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  GetActivityShopSheetInfoRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetActivityShopSheetInfoRsp& from);
  void MergeFrom(const GetActivityShopSheetInfoRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetActivityShopSheetInfoRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GetActivityShopSheetInfoRsp_CmdId CmdId;
  static const CmdId NONE =
    GetActivityShopSheetInfoRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    GetActivityShopSheetInfoRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    GetActivityShopSheetInfoRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    GetActivityShopSheetInfoRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return GetActivityShopSheetInfoRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    GetActivityShopSheetInfoRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    GetActivityShopSheetInfoRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    GetActivityShopSheetInfoRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return GetActivityShopSheetInfoRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return GetActivityShopSheetInfoRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return GetActivityShopSheetInfoRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .proto.ActivityShopSheetInfo sheet_info_list = 6;
  int sheet_info_list_size() const;
  void clear_sheet_info_list();
  static const int kSheetInfoListFieldNumber = 6;
  const ::proto::ActivityShopSheetInfo& sheet_info_list(int index) const;
  ::proto::ActivityShopSheetInfo* mutable_sheet_info_list(int index);
  ::proto::ActivityShopSheetInfo* add_sheet_info_list();
  ::google::protobuf::RepeatedPtrField< ::proto::ActivityShopSheetInfo >*
      mutable_sheet_info_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::ActivityShopSheetInfo >&
      sheet_info_list() const;

  // uint32 shop_type = 8;
  void clear_shop_type();
  static const int kShopTypeFieldNumber = 8;
  ::google::protobuf::uint32 shop_type() const;
  void set_shop_type(::google::protobuf::uint32 value);

  // int32 retcode = 13;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 13;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.GetActivityShopSheetInfoRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::ActivityShopSheetInfo > sheet_info_list_;
  ::google::protobuf::uint32 shop_type_;
  ::google::protobuf::int32 retcode_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BuyGoodsParam : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.BuyGoodsParam) */ {
 public:
  BuyGoodsParam();
  virtual ~BuyGoodsParam();

  BuyGoodsParam(const BuyGoodsParam& from);

  inline BuyGoodsParam& operator=(const BuyGoodsParam& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BuyGoodsParam(BuyGoodsParam&& from) noexcept
    : BuyGoodsParam() {
    *this = ::std::move(from);
  }

  inline BuyGoodsParam& operator=(BuyGoodsParam&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BuyGoodsParam& default_instance();

  static inline const BuyGoodsParam* internal_default_instance() {
    return reinterpret_cast<const BuyGoodsParam*>(
               &_BuyGoodsParam_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    11;

  void Swap(BuyGoodsParam* other);
  friend void swap(BuyGoodsParam& a, BuyGoodsParam& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BuyGoodsParam* New() const PROTOBUF_FINAL { return New(NULL); }

  BuyGoodsParam* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BuyGoodsParam& from);
  void MergeFrom(const BuyGoodsParam& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BuyGoodsParam* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .proto.ShopGoods goods = 13;
  bool has_goods() const;
  void clear_goods();
  static const int kGoodsFieldNumber = 13;
  const ::proto::ShopGoods& goods() const;
  ::proto::ShopGoods* mutable_goods();
  ::proto::ShopGoods* release_goods();
  void set_allocated_goods(::proto::ShopGoods* goods);

  // uint32 buy_count = 12;
  void clear_buy_count();
  static const int kBuyCountFieldNumber = 12;
  ::google::protobuf::uint32 buy_count() const;
  void set_buy_count(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.BuyGoodsParam)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::proto::ShopGoods* goods_;
  ::google::protobuf::uint32 buy_count_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BatchBuyGoodsReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.BatchBuyGoodsReq) */ {
 public:
  BatchBuyGoodsReq();
  virtual ~BatchBuyGoodsReq();

  BatchBuyGoodsReq(const BatchBuyGoodsReq& from);

  inline BatchBuyGoodsReq& operator=(const BatchBuyGoodsReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BatchBuyGoodsReq(BatchBuyGoodsReq&& from) noexcept
    : BatchBuyGoodsReq() {
    *this = ::std::move(from);
  }

  inline BatchBuyGoodsReq& operator=(BatchBuyGoodsReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BatchBuyGoodsReq& default_instance();

  static inline const BatchBuyGoodsReq* internal_default_instance() {
    return reinterpret_cast<const BatchBuyGoodsReq*>(
               &_BatchBuyGoodsReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    12;

  void Swap(BatchBuyGoodsReq* other);
  friend void swap(BatchBuyGoodsReq& a, BatchBuyGoodsReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BatchBuyGoodsReq* New() const PROTOBUF_FINAL { return New(NULL); }

  BatchBuyGoodsReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BatchBuyGoodsReq& from);
  void MergeFrom(const BatchBuyGoodsReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BatchBuyGoodsReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef BatchBuyGoodsReq_CmdId CmdId;
  static const CmdId NONE =
    BatchBuyGoodsReq_CmdId_NONE;
  static const CmdId CMD_ID =
    BatchBuyGoodsReq_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    BatchBuyGoodsReq_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    BatchBuyGoodsReq_CmdId_ENET_IS_RELIABLE;
  static const CmdId IS_ALLOW_CLIENT =
    BatchBuyGoodsReq_CmdId_IS_ALLOW_CLIENT;
  static inline bool CmdId_IsValid(int value) {
    return BatchBuyGoodsReq_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    BatchBuyGoodsReq_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    BatchBuyGoodsReq_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    BatchBuyGoodsReq_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return BatchBuyGoodsReq_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return BatchBuyGoodsReq_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return BatchBuyGoodsReq_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .proto.BuyGoodsParam buy_goods_list = 2;
  int buy_goods_list_size() const;
  void clear_buy_goods_list();
  static const int kBuyGoodsListFieldNumber = 2;
  const ::proto::BuyGoodsParam& buy_goods_list(int index) const;
  ::proto::BuyGoodsParam* mutable_buy_goods_list(int index);
  ::proto::BuyGoodsParam* add_buy_goods_list();
  ::google::protobuf::RepeatedPtrField< ::proto::BuyGoodsParam >*
      mutable_buy_goods_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::BuyGoodsParam >&
      buy_goods_list() const;

  // uint32 shop_type = 7;
  void clear_shop_type();
  static const int kShopTypeFieldNumber = 7;
  ::google::protobuf::uint32 shop_type() const;
  void set_shop_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.BatchBuyGoodsReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::BuyGoodsParam > buy_goods_list_;
  ::google::protobuf::uint32 shop_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BatchBuyGoodsRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.BatchBuyGoodsRsp) */ {
 public:
  BatchBuyGoodsRsp();
  virtual ~BatchBuyGoodsRsp();

  BatchBuyGoodsRsp(const BatchBuyGoodsRsp& from);

  inline BatchBuyGoodsRsp& operator=(const BatchBuyGoodsRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BatchBuyGoodsRsp(BatchBuyGoodsRsp&& from) noexcept
    : BatchBuyGoodsRsp() {
    *this = ::std::move(from);
  }

  inline BatchBuyGoodsRsp& operator=(BatchBuyGoodsRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BatchBuyGoodsRsp& default_instance();

  static inline const BatchBuyGoodsRsp* internal_default_instance() {
    return reinterpret_cast<const BatchBuyGoodsRsp*>(
               &_BatchBuyGoodsRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    13;

  void Swap(BatchBuyGoodsRsp* other);
  friend void swap(BatchBuyGoodsRsp& a, BatchBuyGoodsRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BatchBuyGoodsRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  BatchBuyGoodsRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BatchBuyGoodsRsp& from);
  void MergeFrom(const BatchBuyGoodsRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BatchBuyGoodsRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef BatchBuyGoodsRsp_CmdId CmdId;
  static const CmdId NONE =
    BatchBuyGoodsRsp_CmdId_NONE;
  static const CmdId CMD_ID =
    BatchBuyGoodsRsp_CmdId_CMD_ID;
  static const CmdId ENET_CHANNEL_ID =
    BatchBuyGoodsRsp_CmdId_ENET_CHANNEL_ID;
  static const CmdId ENET_IS_RELIABLE =
    BatchBuyGoodsRsp_CmdId_ENET_IS_RELIABLE;
  static inline bool CmdId_IsValid(int value) {
    return BatchBuyGoodsRsp_CmdId_IsValid(value);
  }
  static const CmdId CmdId_MIN =
    BatchBuyGoodsRsp_CmdId_CmdId_MIN;
  static const CmdId CmdId_MAX =
    BatchBuyGoodsRsp_CmdId_CmdId_MAX;
  static const int CmdId_ARRAYSIZE =
    BatchBuyGoodsRsp_CmdId_CmdId_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdId_descriptor() {
    return BatchBuyGoodsRsp_CmdId_descriptor();
  }
  static inline const ::std::string& CmdId_Name(CmdId value) {
    return BatchBuyGoodsRsp_CmdId_Name(value);
  }
  static inline bool CmdId_Parse(const ::std::string& name,
      CmdId* value) {
    return BatchBuyGoodsRsp_CmdId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .proto.BuyGoodsParam buy_goods_list = 5;
  int buy_goods_list_size() const;
  void clear_buy_goods_list();
  static const int kBuyGoodsListFieldNumber = 5;
  const ::proto::BuyGoodsParam& buy_goods_list(int index) const;
  ::proto::BuyGoodsParam* mutable_buy_goods_list(int index);
  ::proto::BuyGoodsParam* add_buy_goods_list();
  ::google::protobuf::RepeatedPtrField< ::proto::BuyGoodsParam >*
      mutable_buy_goods_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::BuyGoodsParam >&
      buy_goods_list() const;

  // repeated .proto.ShopGoods goods_list = 9;
  int goods_list_size() const;
  void clear_goods_list();
  static const int kGoodsListFieldNumber = 9;
  const ::proto::ShopGoods& goods_list(int index) const;
  ::proto::ShopGoods* mutable_goods_list(int index);
  ::proto::ShopGoods* add_goods_list();
  ::google::protobuf::RepeatedPtrField< ::proto::ShopGoods >*
      mutable_goods_list();
  const ::google::protobuf::RepeatedPtrField< ::proto::ShopGoods >&
      goods_list() const;

  // int32 retcode = 1;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 1;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // uint32 shop_type = 14;
  void clear_shop_type();
  static const int kShopTypeFieldNumber = 14;
  ::google::protobuf::uint32 shop_type() const;
  void set_shop_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.BatchBuyGoodsRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::BuyGoodsParam > buy_goods_list_;
  ::google::protobuf::RepeatedPtrField< ::proto::ShopGoods > goods_list_;
  ::google::protobuf::int32 retcode_;
  ::google::protobuf::uint32 shop_type_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fshop_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================


// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::proto::GetShopReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::GetShopReq_CmdId>() {
  return ::proto::GetShopReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::GetShopRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::GetShopRsp_CmdId>() {
  return ::proto::GetShopRsp_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::BuyGoodsReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::BuyGoodsReq_CmdId>() {
  return ::proto::BuyGoodsReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::BuyGoodsRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::BuyGoodsRsp_CmdId>() {
  return ::proto::BuyGoodsRsp_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::GetShopmallDataReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::GetShopmallDataReq_CmdId>() {
  return ::proto::GetShopmallDataReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::GetShopmallDataRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::GetShopmallDataRsp_CmdId>() {
  return ::proto::GetShopmallDataRsp_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::GetActivityShopSheetInfoReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::GetActivityShopSheetInfoReq_CmdId>() {
  return ::proto::GetActivityShopSheetInfoReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::GetActivityShopSheetInfoRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::GetActivityShopSheetInfoRsp_CmdId>() {
  return ::proto::GetActivityShopSheetInfoRsp_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::BatchBuyGoodsReq_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::BatchBuyGoodsReq_CmdId>() {
  return ::proto::BatchBuyGoodsReq_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::BatchBuyGoodsRsp_CmdId> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::BatchBuyGoodsRsp_CmdId>() {
  return ::proto::BatchBuyGoodsRsp_CmdId_descriptor();
}
template <> struct is_proto_enum< ::proto::ShopGoodsDisableType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::ShopGoodsDisableType>() {
  return ::proto::ShopGoodsDisableType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cmd_2fcmd_5fshop_2eproto__INCLUDED
