// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd/cmd_stat.proto

#ifndef PROTOBUF_cmd_2fcmd_5fstat_2eproto__INCLUDED
#define PROTOBUF_cmd_2fcmd_5fstat_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "define.pb.h"
// @@protoc_insertion_point(includes)
namespace proto {
class AISnapshotEntityData;
class AISnapshotEntityDataDefaultTypeInternal;
extern AISnapshotEntityDataDefaultTypeInternal _AISnapshotEntityData_default_instance_;
class AISnapshotEntityData_HittingAvatarsEntry;
class AISnapshotEntityData_HittingAvatarsEntryDefaultTypeInternal;
extern AISnapshotEntityData_HittingAvatarsEntryDefaultTypeInternal _AISnapshotEntityData_HittingAvatarsEntry_default_instance_;
class AISnapshotEntitySkillCycle;
class AISnapshotEntitySkillCycleDefaultTypeInternal;
extern AISnapshotEntitySkillCycleDefaultTypeInternal _AISnapshotEntitySkillCycle_default_instance_;
class AISnapshotInfo;
class AISnapshotInfoDefaultTypeInternal;
extern AISnapshotInfoDefaultTypeInternal _AISnapshotInfo_default_instance_;
}  // namespace proto

namespace proto {

namespace protobuf_cmd_2fcmd_5fstat_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cmd_2fcmd_5fstat_2eproto

// ===================================================================

class AISnapshotEntitySkillCycle : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.AISnapshotEntitySkillCycle) */ {
 public:
  AISnapshotEntitySkillCycle();
  virtual ~AISnapshotEntitySkillCycle();

  AISnapshotEntitySkillCycle(const AISnapshotEntitySkillCycle& from);

  inline AISnapshotEntitySkillCycle& operator=(const AISnapshotEntitySkillCycle& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AISnapshotEntitySkillCycle(AISnapshotEntitySkillCycle&& from) noexcept
    : AISnapshotEntitySkillCycle() {
    *this = ::std::move(from);
  }

  inline AISnapshotEntitySkillCycle& operator=(AISnapshotEntitySkillCycle&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AISnapshotEntitySkillCycle& default_instance();

  static inline const AISnapshotEntitySkillCycle* internal_default_instance() {
    return reinterpret_cast<const AISnapshotEntitySkillCycle*>(
               &_AISnapshotEntitySkillCycle_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(AISnapshotEntitySkillCycle* other);
  friend void swap(AISnapshotEntitySkillCycle& a, AISnapshotEntitySkillCycle& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AISnapshotEntitySkillCycle* New() const PROTOBUF_FINAL { return New(NULL); }

  AISnapshotEntitySkillCycle* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AISnapshotEntitySkillCycle& from);
  void MergeFrom(const AISnapshotEntitySkillCycle& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AISnapshotEntitySkillCycle* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 skill_id = 2;
  void clear_skill_id();
  static const int kSkillIdFieldNumber = 2;
  ::google::protobuf::uint32 skill_id() const;
  void set_skill_id(::google::protobuf::uint32 value);

  // bool failed = 12;
  void clear_failed();
  static const int kFailedFieldNumber = 12;
  bool failed() const;
  void set_failed(bool value);

  // bool trydoskill = 8;
  void clear_trydoskill();
  static const int kTrydoskillFieldNumber = 8;
  bool trydoskill() const;
  void set_trydoskill(bool value);

  // bool success = 9;
  void clear_success();
  static const int kSuccessFieldNumber = 9;
  bool success() const;
  void set_success(bool value);

  // bool selected = 1;
  void clear_selected();
  static const int kSelectedFieldNumber = 1;
  bool selected() const;
  void set_selected(bool value);

  // @@protoc_insertion_point(class_scope:proto.AISnapshotEntitySkillCycle)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 skill_id_;
  bool failed_;
  bool trydoskill_;
  bool success_;
  bool selected_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fstat_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class AISnapshotEntityData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.AISnapshotEntityData) */ {
 public:
  AISnapshotEntityData();
  virtual ~AISnapshotEntityData();

  AISnapshotEntityData(const AISnapshotEntityData& from);

  inline AISnapshotEntityData& operator=(const AISnapshotEntityData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AISnapshotEntityData(AISnapshotEntityData&& from) noexcept
    : AISnapshotEntityData() {
    *this = ::std::move(from);
  }

  inline AISnapshotEntityData& operator=(AISnapshotEntityData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AISnapshotEntityData& default_instance();

  static inline const AISnapshotEntityData* internal_default_instance() {
    return reinterpret_cast<const AISnapshotEntityData*>(
               &_AISnapshotEntityData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(AISnapshotEntityData* other);
  friend void swap(AISnapshotEntityData& a, AISnapshotEntityData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AISnapshotEntityData* New() const PROTOBUF_FINAL { return New(NULL); }

  AISnapshotEntityData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AISnapshotEntityData& from);
  void MergeFrom(const AISnapshotEntityData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AISnapshotEntityData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<uint32, uint32> hitting_avatars = 7;
  int hitting_avatars_size() const;
  void clear_hitting_avatars();
  static const int kHittingAvatarsFieldNumber = 7;
  const ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >&
      hitting_avatars() const;
  ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >*
      mutable_hitting_avatars();

  // repeated .proto.AISnapshotEntitySkillCycle finished_skill_cycles = 9;
  int finished_skill_cycles_size() const;
  void clear_finished_skill_cycles();
  static const int kFinishedSkillCyclesFieldNumber = 9;
  const ::proto::AISnapshotEntitySkillCycle& finished_skill_cycles(int index) const;
  ::proto::AISnapshotEntitySkillCycle* mutable_finished_skill_cycles(int index);
  ::proto::AISnapshotEntitySkillCycle* add_finished_skill_cycles();
  ::google::protobuf::RepeatedPtrField< ::proto::AISnapshotEntitySkillCycle >*
      mutable_finished_skill_cycles();
  const ::google::protobuf::RepeatedPtrField< ::proto::AISnapshotEntitySkillCycle >&
      finished_skill_cycles() const;

  // uint32 threat_list_size = 1;
  void clear_threat_list_size();
  static const int kThreatListSizeFieldNumber = 1;
  ::google::protobuf::uint32 threat_list_size() const;
  void set_threat_list_size(::google::protobuf::uint32 value);

  // uint32 tactic = 2;
  void clear_tactic();
  static const int kTacticFieldNumber = 2;
  ::google::protobuf::uint32 tactic() const;
  void set_tactic(::google::protobuf::uint32 value);

  // uint32 threat_target_id = 3;
  void clear_threat_target_id();
  static const int kThreatTargetIdFieldNumber = 3;
  ::google::protobuf::uint32 threat_target_id() const;
  void set_threat_target_id(::google::protobuf::uint32 value);

  // float moved_distance = 4;
  void clear_moved_distance();
  static const int kMovedDistanceFieldNumber = 4;
  float moved_distance() const;
  void set_moved_distance(float value);

  // float tick_time = 5;
  void clear_tick_time();
  static const int kTickTimeFieldNumber = 5;
  float tick_time() const;
  void set_tick_time(float value);

  // uint32 attack_target_id = 10;
  void clear_attack_target_id();
  static const int kAttackTargetIdFieldNumber = 10;
  ::google::protobuf::uint32 attack_target_id() const;
  void set_attack_target_id(::google::protobuf::uint32 value);

  // float distance_to_player = 11;
  void clear_distance_to_player();
  static const int kDistanceToPlayerFieldNumber = 11;
  float distance_to_player() const;
  void set_distance_to_player(float value);

  // uint32 ai_target_id = 13;
  void clear_ai_target_id();
  static const int kAiTargetIdFieldNumber = 13;
  ::google::protobuf::uint32 ai_target_id() const;
  void set_ai_target_id(::google::protobuf::uint32 value);

  // float real_time = 14;
  void clear_real_time();
  static const int kRealTimeFieldNumber = 14;
  float real_time() const;
  void set_real_time(float value);

  // uint32 entity_id = 15;
  void clear_entity_id();
  static const int kEntityIdFieldNumber = 15;
  ::google::protobuf::uint32 entity_id() const;
  void set_entity_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.AISnapshotEntityData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  public:
  class AISnapshotEntityData_HittingAvatarsEntry : public ::google::protobuf::internal::MapEntry<AISnapshotEntityData_HittingAvatarsEntry, 
      ::google::protobuf::uint32, ::google::protobuf::uint32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<AISnapshotEntityData_HittingAvatarsEntry, 
      ::google::protobuf::uint32, ::google::protobuf::uint32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      0 > SuperType;
    AISnapshotEntityData_HittingAvatarsEntry();
    AISnapshotEntityData_HittingAvatarsEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const AISnapshotEntityData_HittingAvatarsEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_AISnapshotEntityData_HittingAvatarsEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  private:
  ::google::protobuf::internal::MapField<
      AISnapshotEntityData_HittingAvatarsEntry,
      ::google::protobuf::uint32, ::google::protobuf::uint32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      0 > hitting_avatars_;
  private:
  ::google::protobuf::RepeatedPtrField< ::proto::AISnapshotEntitySkillCycle > finished_skill_cycles_;
  ::google::protobuf::uint32 threat_list_size_;
  ::google::protobuf::uint32 tactic_;
  ::google::protobuf::uint32 threat_target_id_;
  float moved_distance_;
  float tick_time_;
  ::google::protobuf::uint32 attack_target_id_;
  float distance_to_player_;
  ::google::protobuf::uint32 ai_target_id_;
  float real_time_;
  ::google::protobuf::uint32 entity_id_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fstat_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AISnapshotInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.AISnapshotInfo) */ {
 public:
  AISnapshotInfo();
  virtual ~AISnapshotInfo();

  AISnapshotInfo(const AISnapshotInfo& from);

  inline AISnapshotInfo& operator=(const AISnapshotInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AISnapshotInfo(AISnapshotInfo&& from) noexcept
    : AISnapshotInfo() {
    *this = ::std::move(from);
  }

  inline AISnapshotInfo& operator=(AISnapshotInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AISnapshotInfo& default_instance();

  static inline const AISnapshotInfo* internal_default_instance() {
    return reinterpret_cast<const AISnapshotInfo*>(
               &_AISnapshotInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(AISnapshotInfo* other);
  friend void swap(AISnapshotInfo& a, AISnapshotInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AISnapshotInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  AISnapshotInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AISnapshotInfo& from);
  void MergeFrom(const AISnapshotInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AISnapshotInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto.AISnapshotEntityData ai_snapshots = 13;
  int ai_snapshots_size() const;
  void clear_ai_snapshots();
  static const int kAiSnapshotsFieldNumber = 13;
  const ::proto::AISnapshotEntityData& ai_snapshots(int index) const;
  ::proto::AISnapshotEntityData* mutable_ai_snapshots(int index);
  ::proto::AISnapshotEntityData* add_ai_snapshots();
  ::google::protobuf::RepeatedPtrField< ::proto::AISnapshotEntityData >*
      mutable_ai_snapshots();
  const ::google::protobuf::RepeatedPtrField< ::proto::AISnapshotEntityData >&
      ai_snapshots() const;

  // @@protoc_insertion_point(class_scope:proto.AISnapshotInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::AISnapshotEntityData > ai_snapshots_;
  mutable int _cached_size_;
  friend struct protobuf_cmd_2fcmd_5fstat_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================


// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cmd_2fcmd_5fstat_2eproto__INCLUDED
